FreeTubeApp/FreeTube

- README.md
>  Add Google API disclaimer to README.md and correct statments

- src/js/channels.js
- src/js/events.js
- src/js/history.js
- src/js/init.js
- src/js/layout.js
- src/js/savedVideos.js
- src/js/settings.js
- src/js/subscriptions.js
- src/js/videos.js
- src/js/youtubeApi.js
- src/templates/about.html
- src/templates/channelView.html
Refactor code to make it more readable.
* Don't create variables if they are only used once.
* Use object.key instead of object['key'].
* videos.js: rename displayVideos() to displayVideo()
* remove comments pointing out obvious things
* don't display toast when trying to search without a term
> Refactor code

- src/js/savedVideos.js
- src/js/videos.js
Simple fix to remove typo causing "#46 Imposible to remove saved video" and some cleanup
- [ X ] I have read and agree to the [Contribution Guidelines](https://github.com/FreeTubeApp/FreeTube/blob/master/CONTRIBUTING.md)
- [ X ] I can maintain / support my code if issues arise.
>  Resolved, #46 Imposible to remove saved video

- src/js/videos.js
- [ x] I have read and agree to the [Contribution Guidelines](https://github.com/FreeTubeApp/FreeTube/blob/master/CONTRIBUTING.md)
- [ x] I can maintain / support my code if issues arise.
> Changed try/catch to if/else statement and parsed Channel/User functionality

- README.md
Fixed advertisements and instructions in README.md
Just a few spelling mistakes that I found. I really like the project, I found the spelling mistakes while looking over the documentation.
> Fix two spelling mistakes

- src/js/player.js
This change is kind of a shortcut that is a temporary fix before FreeTube migrates to using the adaptive formats to choose the streaming option URLs.
> Choose higher-quality audio stream URL

- locales/en-US.json
- locales/es.json
- As in #182 @grrrrr tell, it is necessary to change this string according to last changes: "Favorited/Favoritos" instead of "Saved/Guardados".
The commit said "fix #182" but it is fixed partially, because I could change only this two strings in English and Spanish. I might try to change in other languages like German, French and Italian, but it would be better if someone native or with a good level would do it.
> Change "Favorited" to "Saved"

- src/js/history.js
Update to history functionality. Check if video already exist in history. If it does then update timestamp of history item instead of adding a new one.
Would close https://github.com/FreeTubeApp/FreeTube/issues/202
> Remove duplicates from history

- src/index.html
- src/js/templates.js
- src/style/main.css
Adds a back button to Search and Playlist.
- When you are in Search view and click on channel, video or playlist then back button will be displayed that will take you back to search results.
- When you are in a Playlist view and click on video or channel then back button will be displayed that will take you back to Playlist view.
> Add back button for searchView and playlistView

- src/js/templates.js
> Hide loading view after clicking on back button

- src/js/settings.js
- src/templates/settings.html
Enhancement https://github.com/FreeTubeApp/FreeTube/issues/125
> Implement importing of Newpipe Subscriptions 

- package-lock.json
- src/js/layout.js
These are the patches I made as part of flatpaking FreeTube. I'm submitting them here because non-flatpak users should also benefit from them.
> Update package-lock.json and use final command-line arg as url

- src/js/settings.js
- src/templates/settings.html
Support export as NewPipe & OPML formats.
> Add support to export as Newpipe & OPML formats

- src/js/init.js
This is the patch I wrote to fix flathub/io.freetubeapp.FreeTube#7. #257 might be related.
> Explicitly set the window icon on Linux

- src/style/main.css
- src/style/videoGrid.css
- src/templates/videoTemplate.html
Show videos in grid with equal space between them
Show videos in a grid with equal space between them
Fixes #296 .
> Add a Flex Grid to display videos

- src/js/channels.js
- src/js/player.js
- src/js/subscriptions.js
- src/js/videos.js
- src/templates/videoTemplate.html
> Use ellipsis character (…) instead of three dots (...)

- src/js/init.js
> preserve window "maximized" state, closes #298

- package.json
1."Video" dont work with mate
2.I think that "Network" would be better
> changed linux category

- src/js/templates.js
- src/style/playlist.css
- src/templates/playlistView.html
closes #363 
Adds Share Button on Playlist View page.
Includes:
- Copy YouTube Playlist Link
- Copy Invidious Playlist Link
- Open in YouTube
- Open in Invidious
> Add Share Playlist button to Playlist View

- src/js/templates.js
- src/js/videos.js
- src/templates/player.html
- src/templates/playlistView.html
- src/templates/videoTemplate.html
This PR closes #331 
Adds YouTube-NoCookie buttons to all share buttons and kebab menues for videos
> Add YouTube-NoCookie to share and kebab menu

- package.json
> added portable(win64) support

- src/js/templates.js
- src/templates/player.html
Adds checkbox for #332
Wasn't too sure if there was a better styling option for this, the material 'switch' checkbox wouldn't fit in the share dropdown. 
Also the time parameter doesn't seem to work for youtube-nocookie so it was left out.
> Added 'current time' option to share menu as a checkbox.

- README.md
---
Updated the Freetube screenshot, to the 0.8.0 rewrite UI 
---
As the previous one were directly hosted on the Freetube website, they may be re-uploaded later on.
I’ve also edited the previous width size of those, as they were taken in a different resolution, allowing for a wider showcase resolution.
I’ll apologize, if the 0.8.0 redesign, was still supposed to be a work-in-progress.
> Updated the Freetube screenshots, to the 0.8.0 rewrite UI 

- src/renderer/main.js
---
Language sorting & Bulgarian language
---
Please link the issue your pull request is referring to.
I sorted the available languages by their international language abbreviation so they are easier to check for not yet added languages.
> Sorted languages by language abbreviation and added bulgarian

- src/renderer/main.js
---
Added languages Greek, Hebrew, Portuguese, Slovenian
---
> Added languages Greek, Hebrew, Portuguese, Slovenian

- CONTRIBUTING.md
---
Added the contribution file back in
---
Closes #566
> Added the contribution file back in

- package-lock.json
- package.json
---
Updated comment scraper to fix like bug
---
Closes issue #634
Upstream fix
> Updated comment scraper to fix like bug

- src/renderer/components/ft-list-video/ft-list-video.js
> Recommended live video shows live tag, instead of undefined

- src/renderer/components/ft-search-filters/ft-search-filters.vue
- src/renderer/components/ft-slider/ft-slider.js
- src/renderer/components/ft-slider/ft-slider.vue
- src/renderer/components/player-settings/player-settings.vue
#632 
Alignment and typography corrections - please see my comments in the commits
Not tested
- OS: [Mac OS]
- OS Version: [10.11.6]
- FreeTube version: [0.9]
> Alignment and typography corrections

- package-lock.json
- package.json
- src/renderer/components/watch-video-comments/watch-video-comments.css
- src/renderer/components/watch-video-comments/watch-video-comments.js
- src/renderer/components/watch-video-comments/watch-video-comments.vue
- src/renderer/views/Watch/Watch.vue
- Feature Implementation
Should close #655
This PR appends a badge to comments that were loved by the creator
**Desktop:**
- FreeTube version: development HEAD
> Display heart badge on loved comments

- package.json
---
Updated Comment module
---
Please link the issue your pull request is referring to.
- OS: [e.g. iOS]
- OS Version: [e.g. 22]
- FreeTube version: [e.g. 0.8] …
> Updated Comment module

- src/renderer/main.js
Czech language is added, but not enabled. Enable Czech translation
---
Title
---
- [ X] Feature Implementation
> Czech language is added, but not enabled. Enable Czech translation

- .github/workflows/flatpak.yml
- .github/workflows/release.yml
- package.json
This PR creates new workflows for GitHub Actions. This allows for a one-click action to upload binaries to a new release draft.
Once the release is published, the second action will be triggered which will create a PR to the Flathub repository with the required changes for the Flathub release.
> New Workflows for Automated Release

- package-lock.json
- src/renderer/components/ft-auto-grid/ft-auto-grid.sass
- src/renderer/components/ft-icon-button/ft-icon-button.sass
- src/renderer/components/ft-icon-button/ft-icon-button.vue
- src/renderer/components/ft-list-video/ft-list-video.vue
- src/renderer/sass-partials/_ft-list-item.sass
---
This is the discussion PR for enhancing the watched video's appearance. provided by @cloudrac3r [comment](https://github.com/FreeTubeApp/FreeTube/issues/558#issuecomment-731572287)
---
#558 
This PR is intended to discuss, how should be the "watched" video appearance on FreeTube.
Has this pull request been tested? - Yes
Please describe shortly how you tested it and whether there are any ramifications remaining. …
> Enhancing "watched" videos appearance

- src/renderer/main.js
---
Added Galician as activated language
---
Galician is now at a high enough percentage to be usable as a language in the app
- OS: Windows
- FreeTube version: v10.0.0
> Added Galician as activated language

- src/renderer/store/modules/playlist.js
---
Adding playlist database logic
---
N/A
Updated playlist.js with state, getters, mutations, and actions
N/A
The updates have not been tested.
This file is not currently used.
- OS: Linux Xubuntu
- OS Version: 20.04
- FreeTube version: 0.9.2
The purpose of this pull request is to get feedback on the store/database business logic and align on expected functionality before proceeding further with playlists …
> Adding playlist database logic

- package-lock.json
- package.json
---
Update of Trending Scraper module
---
Upstream module now uses the newest axios version and also scrapes video correctly again
- OS: Win
- FreeTube version: 11.0.0
> Update of Trending Scraper module

- src/renderer/views/Watch/Watch.js
Fixes #1074
Making things better, one line at a time...
> Include publishedText for recommendations (local)

- src/renderer/main.js
---
Enabled Norwegian Bokmal and Ukrainian as languages
---
Norwegian Bokmal and Ukrainian have reached sufficient percentages in translation to be usable in the application.
It was checked whether important pages are translated or whether the english translation was left in
- OS: Win
> Enabled Norweguan Bokmal and Ukrainian as languages

- src/renderer/components/side-nav/side-nav.vue
> Set a fixed width for side-bar icons

- package-lock.json
- package.json
- src/renderer/main.js
---
New languages and yt-channel-info bump
---
The languages Icelandic and Norwegian Nynorsk are now available to choose from. Additionally the yt-channel-info module was brought on par for further development.
Tested in dev mode that the channels still work.
- OS: Windows
- FreeTube version: 12.0.0
> New languages and yt-channel-info bump

- package-lock.json
---
Title
---
Please link the issue your pull request is referring to.
- OS: [e.g. iOS]
- OS Version: [e.g. 22]
- FreeTube version: [e.g. 0.8]
**Additional …
> Fixed package-lock

- src/renderer/views/Watch/Watch.js
---
Svallinns locale fix
---
Checks whether the locale exists to prevent erroring out.
- OS: Windows
- FreeTube version: v12.0.0
> Svallinns locale fix

- package-lock.json
- package.json
---
Bumped yt-channel-info
---
Bump of yt-channel-info to include the channel loading fix and potential performance boost flag
> Bumped yt-channel-info

- src/main/index.js
- src/renderer/components/top-nav/top-nav.js
- src/renderer/components/top-nav/top-nav.sass
- src/renderer/components/top-nav/top-nav.vue
- Closes #1122 
Adds a button to top nav
A new window is created when this new button is pressed
This button is only shown on wide windows (reverse of search container toggle button)
Tested via these steps
- Run app via `npm run debug`
- Press button to open new window(s)
- Close old window(s), especially the initially created one
- Ensure no error raised in main process
Issues encountered during development:
**1. `Object has been destroyed`**
caused by accessing `mainWindow.webContents`, due to `mainWindow` points to a closed window
**2. Duplicate Application Menu Items**
The menu created …
> Add "open new window" button

- src/renderer/components/ft-input/ft-input.js
- src/renderer/components/ft-input/ft-input.vue
- src/renderer/components/top-nav/top-nav.vue
- src/renderer/views/Channel/Channel.vue
> Select text when focusing/clicking search-related input text boxes

- src/renderer/App.js
- src/renderer/App.vue
- src/renderer/store/modules/profile.js
Closes #552
**Desktop**
- FreeTube version: development
> Bugfix: load of subscriptions at startup

- src/renderer/views/Watch/Watch.js
Closes #878 
This PR makes it so that, when a user closes a window that is currently playing a video, the app saves the current timestamp of the video before closing itself.
**Desktop**
- FreeTube version: development
> Save watch progress when closing window

- package-lock.json
- package.json
---
Bumped trending module
---
Module now accounts for the possibility of missing view count on videos like the google earth day doodle
> Bumped trending module

- src/renderer/views/Watch/Watch.js
https://github.com/FreeTubeApp/FreeTube/issues/1214
Instead of just showing "Playing next video in N seconds. Click ..." 1 time
Show that message with remaining of seconds until cancelled or jumped to next video
See attached video
Countdown without cancel
https://user-images.githubusercontent.com/1018543/116199247-7d44d600-a769-11eb-9790-c4a394d0d361.mp4
- OS: MacOS
- …
> * Implement playlist countdown per second

- src/renderer/components/ft-video-player/ft-video-player.js
- src/renderer/components/player-settings/player-settings.js
- src/renderer/components/player-settings/player-settings.vue
- src/renderer/store/modules/settings.js
- static/locales/en-US.yaml
---
Setting to enable and disable display of video play button
---
Yesterday I merged the pr to disable the play button. We now decided that a setting should be used, so I added it in.
Tested on builds
- OS: Windows
- FreeTube version: 13.0.0
> Setting to enable and disable display of video play button

- package-lock.json
- package.json
---
Bumped yt-comment-scraper to fix #1386
---
#1386 
Module bumped to include the fix
Tested on provided videos from PR
- OS: Windows
- FreeTube version: v13.0.1
> Bumped yt-comment-scraper to fix #1386

- src/renderer/components/ft-profile-bubble/ft-profile-bubble.js
- src/renderer/components/ft-profile-edit/ft-profile-edit.js
- src/renderer/components/ft-profile-selector/ft-profile-selector.js
---
Fix emoji initials in Profile Previews
---
closes #1396
Modifies profileName.slice(0,1) to use Array.from(profileName)[0] instead
I tested this by Editing, Adding and viewing a profile
- OS: Windows
- FreeTube version: 0.13.1
> Fix emoji initials in Profile Previews

- src/renderer/store/modules/invidious.js
---
yewtu.be now support FreeTube
---
N/A
This PR allows yewtu.be to be listed in the supported Invidious instances list in the settings.
N/A
I tested by setting `https://yewtu.be` in `Instance Individious` and everything seems to work fine when `prefered API Backend` is set to Invidious. 
- OS: ArchLinux
- OS Version: Rolling release
- FreeTube version: v0.13.2 Beta
N/A
> yewtu.be now support FreeTube

- .github/workflows/linter.yml
---
[Github Action] update linter node-version
---
Might fix linter action keeps failing on PRs
I updated the node-version of the linter
Yes, I added an updated version to the linter to my branch and created a pr to test it (so it might work?)
- OS: Windows
> [Github Action] update linter node-version

- CONTRIBUTING.md
---
Update outdated link in CONTRIBUTING.md
---
none
Update an outdated wiki link in CONTRIBUTING.md. It now links to the new wiki - getting started page.
> Update outdated link in CONTRIBUTING.md

- README.md
---
Linked documentation in readme
---
closes https://github.com/FreeTubeApp/FreeTube/issues/1586
I added the missing link to the documentation. 
None.
Does not apply.
Also doesn't apply here.
None.
> Link documentation in readme

- package.json
- yarn.lock
closes #1722
App start up caused by `@freetube/youtube-chat` requiring `tslib` but package not found
This seems to be caused by `@freetube/youtube-chat` declaring `tslib` in `devDependencies` not `dependencies`
N/A
This PR will start a build and the built artifacts can be used for testing
> Fix nightly build app startup caused by missing `tslib`

- src/renderer/components/watch-video-recommendations/watch-video-recommendations.css
- src/renderer/components/watch-video-recommendations/watch-video-recommendations.vue
---
Make autoplay text fit inside top bar when translated
---
closes #1300
Before fix
After fix
**Testing**
Looks good
> Make autoplay text fit inside top bar when translated

- src/renderer/components/ft-input/ft-input.js
- src/renderer/components/ft-input/ft-input.vue
- static/locales/en-US.yaml
- static/locales/en_GB.yaml
---
Invidious instance autofill
---
Closes #1776
This PR will filter the invidious instance list when you start typing
Type in box, navigate with arrows and click enter, click on item
- OS: Windows
- FreeTube version: 0.15.0 Beta
> Feat: Invidious instance autofill

- src/renderer/App.js
- src/renderer/store/modules/invidious.js
- static/invidious-instances.json
---
Fix: white screen when invidious instances don't load
---
https://github.com/FreeTubeApp/FreeTube/issues/1689#issuecomment-926460495
Not sure if it closes the original issue but it fixes the issue mentioned in the comment
File fallback & hardcoded fallback when api to retrieve instances fails …
> fix: white screen when invidious instances don't load

- src/renderer/components/watch-video-comments/watch-video-comments.css
- src/renderer/components/watch-video-comments/watch-video-comments.js
- src/renderer/components/watch-video-comments/watch-video-comments.vue
- src/renderer/views/Watch/Watch.vue
- static/locales/en-US.yaml
---
Add pinned, owner and reply from owner indicators for comments
---
closes #1433 
closes #1432 
closes #1431 
This PR adds visual indicators for pinned comments, comments by video owner and comments that were replied to by owner.
Light theme:
Dark theme:
Black theme:
Dracula theme:
Has this pull …
> Feature: Add pinned, owner and reply from owner indicators for comments

- package.json
- yarn.lock
N/A
Update electron to latest 15.x
Multiple CVE fixes included in latest 15.x
N/A
- OS: MacOS
- OS Version: 12.0.1
- FreeTube version: aaa295222dec756f3894828046c8c17ffe2eb1ef
> ^ Update electron to latest 15.x

- src/renderer/components/watch-video-comments/watch-video-comments.js
---
Don't repeat comments
---
closes #1985
This pr will stop the comment reply list from getting appended to if the last comment in the list has the same id as the last comment in the current request.
Yes, I spam clicked the view replies button
- OS: Windows
- FreeTube version: Latest nightly
> Fix: Don't repeat comment replies

- package.json
- yarn.lock
---
Title
---
N/A
Update electron to [16.0.9](https://github.com/electron/electron/releases/tag/v16.0.9)
Several security fixes included
Update electron to [16.0.10](https://github.com/electron/electron/releases/tag/v16.0.10)
Several CVE fixes included
N/A
Nope
- OS: MacOS
- FreeTube version: 5aae685a7516b09630aa72879995978b7cdb9be0
Add any …
> ^ Update electron 16.x

- package.json
- yarn.lock
---
Fix randomly occurring error when searching
---
I haven't created an issue for this.
Randomly I have been experiencing issues when searching, I'm not sure what the cause is. Interestingly updating ytsr to the latest release (3.6.0), seems to have fixed the issue for me. This pull request implements that dependency version bump.
Yes, I have been running this for a few days without any issues.
**Desktop (please complete the following …
> Fix randomly occurring error when searching

- package.json
- yarn.lock
---
Title
---
N/A
Update electron to [16.2.0](https://github.com/electron/electron/releases/tag/v16.2.0)
CVE fixes included
Update electron to [16.1.1](https://github.com/electron/electron/releases/tag/v16.1.1)
CVE fixes included
Update electron to [16.1.0](https://github.com/electron/electron/releases/tag/v16.1.0)
Several security fixes included
N/A
N/A
- OS: MacOS …
> Update electron to 16.2.0

- .github/workflows/remove-outdated-labels.yml
- README.md
---
Remove labels after PR closes or being merged
---
closes https://github.com/FreeTubeApp/FreeTube/issues/1720
**Dependent PR/issue**
Please link the pull request or issue your pull request is dependent on to be merged or closed before merging this pull request. Put "depends on" or "blocked by" before the issue number. Example: "blocked by #" or "depends on #".
Removes all labels when PR is closed or …
> Auto Remove outdated labels

- .github/workflows/label-changes-requested.yml
---
Auto Label changes requested
---
Partially addresses https://github.com/FreeTubeApp/FreeTube/issues/1720
**Dependent PR/issue**
Please link the pull request or issue your pull request is dependent on to be merged or closed before merging this pull request. Put "depends on" or "blocked by" before the issue number. Example: "blocked by #" or "depends on #".
blocked by #2183
Adds a label when changes are …
> Auto Label PR changes requested

- .github/workflows/conflicts.yml
- README.md
---
Auto Label Conflicts
---
Partially addresses #1720 
blocked by #2183 
Checks if PR has conflict. If it has conflicts it will add an label, remove the waiting for review label and a comment to notify the author of the PR. When conflicts are resolved it will remove the label, add the waiting for review label and add a comment to confirm that the conflicts are resolved.
None.
1. go to https://github.com/efb4f5ff-1298-471a-8973-3d47447115dc/FreeTube/tree/conflicts
2. change …
> Auto PR Label Conflicts

- .github/workflows/autoLabelDuplicate.yml
- .github/workflows/dependent-issues.yml
- .github/workflows/remove-outdated-labels.yml
---
test workflow API rate limit exceeded
---
testing if workflow exceeds api rate limit
> test workflow API rate limit exceeded

- .github/workflows/autoLabelDuplicate.yml
- .github/workflows/remove-outdated-labels.yml
---
Auto label duplicate issues
---
Automatically adds the duplicate label if u comment with the keywords "duplicate of"
1. open up an issue https://github.com/efb4f5ff-1298-471a-8973-3d47447115dc/FreeTube/issues/new/choose
2. comment with duplicate of issuenumber
removed unnecessary code
> Auto label duplicate issues

- .github/workflows/autoLabelPR.yaml
- .github/workflows/conflicts.yml
- .github/workflows/label-changes-requested.yml
---
testing workflow
---
Testing if the workflow works with new secret
> testing workflow

- package.json
- yarn.lock
N/A
Update electron to [16.2.5](https://github.com/electron/electron/releases/tag/v16.2.5)
**Multiple** CVE fixes included
Update electron to [16.2.4](https://github.com/electron/electron/releases/tag/v16.2.4)
**Multiple** CVE fixes included
Update electron to [16.2.3](https://github.com/electron/electron/releases/tag/v16.2.3)
CVE fixes included
N/A
N/A
- OS: MacOS
- FreeTube version: e29d041a91fe78e96b62ac8cd61d8d8a78797ab7
> Update electron to 16.2.5

- package.json
- yarn.lock
---
Title
---
Update electron to [16.2.6](https://github.com/electron/electron/releases/tag/v16.2.6)
**Multiple** CVE fixes included
N/A
N/A
- OS: MacOS
- FreeTube version: 252f85c49f91c02c959714ff911d65f0d4adcfd6 …
> Update electron to 16.2.6

- package.json
- yarn.lock
---
Title
---
Update electron to [16.2.7](https://github.com/electron/electron/releases/tag/v16.2.7)
**Multiple** CVE fixes included
N/A
N/A
- OS: MacOS
- FreeTube version: 6b3874e8c908e142699db6c2b5a20d345dd667e0 …
> Update electron to 16.2.7

- README.md
---
Browser extension warning
---
Added a warning about why u may not want to install this browser extension
**Additional information**
Also added it to the docs https://github.com/FreeTubeApp/FreeTube-Docs/pull/21
> Browser extension warning

- README.md
---
Added the official windows package manager to readme
---
related https://github.com/FreeTubeApp/FreeTube/discussions/2057
added the package manger to the readme
None.
None.
None.
None
> add winget package manager to readme

- src/renderer/components/ft-list-video/ft-list-video.js
- src/renderer/components/watch-video-info/watch-video-info.js
- src/renderer/store/modules/utils.js
- Feature Implementation
Read the commit message, pretty simple stuff
> Utils+Everywhere: Add a start offset tolerance for the external player

- package.json
- yarn.lock
N/A
Fixes build task on MacOS 12.3+
Reported in https://github.com/electron-userland/electron-builder/issues/6726
Error message before update
- Update to MacOS 12.4
- `yarn run build`
- OS: MacOS
- OS Version: 12.4
- FreeTube version: e861e70b3374b10430a3f657b626c7f14fc22bea
> Update electron-builder version to ^23.0.2

- src/renderer/components/ft-input/ft-input.js
https://github.com/FreeTubeApp/FreeTube/discussions/2309#discussioncomment-2934372
>search something -> see search suggestions -> navigate through the suggestions with the arrow keys on your key board -> get stuck
<video src="https://user-images.githubusercontent.com/80553357/175103121-5d055ead-8abb-4e93-ad7b-4b1ddc64a985.mp4">
- OS: Windows 10 21H1
- FreeTube version: 0.17rc
> fix: search suggestion get stuck

- src/renderer/components/ft-input/ft-input.js
https://github.com/FreeTubeApp/FreeTube/discussions/2309#discussioncomment-2934372
>search something -> see search suggestions -> navigate through the suggestions with the arrow keys on your key board -> get stuck
<video src="https://user-images.githubusercontent.com/80553357/175103121-5d055ead-8abb-4e93-ad7b-4b1ddc64a985.mp4">
- OS: Windows 10 21H1
- FreeTube version: 0.17rc
> fix: search suggestion get stuck [rc]

- static/locales/en-US.yaml
---
Added warning to external player tooltip
---
https://github.com/FreeTubeApp/FreeTube/issues/2373
Add a warning to the already existing tooltip message.
I checked if the text has changed
- OS: win10
- OS Version: 21h2
> Added warning to external player tooltip

- package.json
- yarn.lock
#1788 follow up
Update lefthook to latest version (also the package's namespace is updated)
N/A
N/A
- OS: MacOS
- FreeTube version: N/A
> Update lefthook to latest version

- .github/workflows/autoLabelIssue.yaml
Refactor workflow config file added in #2553
Refactor workflow config file added in #2553
https://codebeautify.org/yaml-parser-online
- OS: N/A
- OS Version: N/A
- FreeTube version: N/A
> Update auto-label-issue GH workflow config to use multiline

- src/renderer/components/watch-video-playlist/watch-video-playlist.js
- src/renderer/views/Channel/Channel.js
- src/renderer/views/Settings/Settings.vue
- src/renderer/views/Trending/Trending.js
- src/renderer/views/Watch/Watch.js
---
Fix some web issues and cleanup
---
Discussion on PR #2574
This PR fixes web specific issues mentioned on #2574 it also cleans up some code and disables fallback to the local API on for web builds, as the web builds only use the Invidious API.
**Testing**
I tested that everything still worked with the Electron build with `yarn dev` and `yarn build`. As there are still a bunch of other web exclusive issues, we can't currently build a web build with the code in the main FreeTube repo.
@MarmadileManteater Could you please test these changes to see if they work with the web build on your fork? (Hopefully some day we'll have a working web build in this repo too).
**Desktop:**
- OS: Windows
- OS …
> Fix some web issues and cleanup

- static/locales/ur.yaml
https://github.com/FreeTubeApp/FreeTube/issues/673#issuecomment-1261220468
Fixes the broken Urdu language, should hopefully fix Weblate as well.
vscode didn't scream at me about invalid YAML syntax afterwards
> Fix broken urdu language

- .github/dependabot.yml
> Include github actions in dependabot workflow

- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/feature_request.yaml
This will hopefully prevent more duplicate issues
> Changed wording on issue templates

- README.md
https://github.com/FreeTubeApp/FreeTube/pull/2553#issuecomment-1241962466
Created a navigation heading for people to navigate quick through our readme. 
Also added a few external links to:
- website
- blog
- faq
- documentation
> Navigation headings for Readme

- src/renderer/components/ft-video-player/ft-video-player.js
- src/renderer/components/ft-video-player/ft-video-player.vue
- src/renderer/views/Watch/Watch.js
This pull request removes the remaining jquery in the ft-player component and the Watch page.
- Video plays
- Changing quality
- Loop
- Full window
- Theatre mode
- Cursor auto hide
- Picture in picture
nearly there 🐌
> Remove jquery from the ft-player component

- package.json
- yarn.lock
N/A
Update to electron [20.3.1](https://github.com/electron/electron/releases/tag/v20.3.1) with CVE fixes
Nope
- **OS:** MacOS
- **OS Version:** 12.6
- **FreeTube version:** e6144571aacf6cbdbcd71995c0f924845e06be20
> ^ Update electron 20.x

- src/renderer/App.js
- src/renderer/components/data-settings/data-settings.js
- src/renderer/components/ft-list-video/ft-list-video.js
- src/renderer/components/ft-profile-channel-list/ft-profile-channel-list.js
- src/renderer/components/ft-profile-edit/ft-profile-edit.js
- src/renderer/components/ft-profile-filter-channels-list/ft-profile-filter-channels-list.js
- src/renderer/components/ft-profile-selector/ft-profile-selector.js
- src/renderer/components/ft-share-button/ft-share-button.js
- src/renderer/components/ft-sponsor-block-category/ft-sponsor-block-category.js
- src/renderer/components/ft-toast/ft-toast.js
- src/renderer/components/ft-video-player/ft-video-player.js
- src/renderer/components/general-settings/general-settings.js
- src/renderer/components/playlist-info/playlist-info.js
- src/renderer/components/privacy-settings/privacy-settings.js
- src/renderer/components/proxy-settings/proxy-settings.js
- src/renderer/components/top-nav/top-nav.js
- src/renderer/components/watch-video-comments/watch-video-comments.js
- src/renderer/components/watch-video-info/watch-video-info.js
- src/renderer/components/watch-video-playlist/watch-video-playlist.js
- src/renderer/helpers/utils.js
- src/renderer/store/modules/settings.js
- src/renderer/store/modules/utils.js
- src/renderer/views/Channel/Channel.js
- src/renderer/views/ProfileEdit/ProfileEdit.js
- src/renderer/views/Search/Search.js
- src/renderer/views/SubscribedChannels/SubscribedChannels.js
- src/renderer/views/Subscriptions/Subscriptions.js
- src/renderer/views/Trending/Trending.js
- src/renderer/views/Watch/Watch.js
This pull request refactors the showToast function from a store action to a normal function that can be imported and used like any other function.
Easy ways to get a toast to show up:
- switch profile
- set or unset the default invidious instance
- have autoplay enabled and go to the end of a video, you'll get the countdown toast
> Make showToast a helper

- package.json
Bumping version number for RC builds so users wont be confused when reporting issues
> Bump version number to v0.22.0

- package.json
- src/botGuardScript.js
- src/constants.js
- src/main/index.js
- src/main/poTokenGenerator.js
- src/renderer/components/ft-shaka-video-player/ft-shaka-video-player.js
- src/renderer/helpers/api/invidious.js
- src/renderer/helpers/api/local.js
- src/renderer/views/Watch/Watch.js
- yarn.lock
> [Master] Bump package version from 0.23.2 to 0.23.3

- package.json
- src/main/index.js
- src/renderer/helpers/api/local.js
- yarn.lock
> [Master] Bump package version from 0.23.3 to 0.23.4

- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/workflows/build.yml
- .github/workflows/release.yml
- _scripts/build.js
- _scripts/ebuilder.config.js
- package.json
- src/renderer/helpers/api/local.js
> [Master] Bump package version from 0.23.4 to 0.23.5

- .github/workflows/updateSite.yml
- package.json
- yarn.lock
- Test if all functionality added works correctly
~Required: #8027~
> Hotfix release - v0.23.9
