FreeTubeApp/FreeTube

src/style/darkTheme.css
src/style/lightTheme.css
src/style/loading.css

This patch moves the background-color property for the .double-bounce1 and .double-bounce2 classes from loading.css into the css for both base themes. This will allow for the easier creation of themes by the community.

Move background-color property in loading.css to *Theme.css

---

package.json

Fix the build error with `npm run make:linux:x86:flatpak`. This was being caused because `electron-installer-flatpak` using out dated library versions by default.
Note: Similarly to the appimage, tor doesn't work in flatpak. See #161

Fix flatpak building

---

locales/de.json
locales/en-US.json
locales/es.json
locales/it.IT.json
locales/nl.json
locales/ru.json

A variable in .json files has been written twice.
Fixed an issue about a duplicated variable in translation files.
This pull request fixes #173

i18n: fix duplicated variable in translation files

---

src/js/subscriptions.js

Accurate info on when premium content is published is currently not available from the Invidious API, so this fix filters it out. 
Of note is that some premium content is still watchable without having a subscription, and can be filtered using the `paid` attribute. A better fix might be to cache premium content in some way in order to provide a consistent `published` time.
Before:
After:
Would close #198 and #208.

Filter premium content from descriptions

---

src/js/templates.js

Updates toggleSave method on videos in videoListTemplate to actually remove videos from Favorites if it's already added.
It also solves an issue where there is no way to remove videos from Favorites without going to Video view page.
Update 02.18.2019: Only update this in savedView because it only really makes sense there.

[Fix] Toggle saved video in videoListTemplate

---

CONTRIBUTING.md

Remove API Keys section from CONTRIBUTING.md as it is no longer relevant and might confuse new contributors.

Remove API Keys section from CONTRIBUTING.md

---

src/js/history.js

I found an issue with history having inconsistent order. 
Steps to recreate: 
1. Clear history
2. Watch 3 videos to add them to your history
3. Switch between Settings and History tabs multiple times and you will see that videos are in different order every time.
That happens because position counter is updated in callback line 70 in below code sample.
https://github.com/FreeTubeApp/FreeTube/blob/2bb080e833a8fa3a4c687dac744e5c0761d55ebf/src/js/history.js#L65-L72
To avoid that use built in index from [forEach](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach#Parameters) instead of external counter.

[Fix] Inconsistent order in history

---

package-lock.json
package.json
src/js/init.js
src/js/layout.js
src/js/settings.js
src/js/templates.js
src/js/youtubeApi.js
src/style/main.css
src/templates/settings.html

Update tor support by using electron's [setProxy](https://electronjs.org/docs/api/session#sessetproxyconfig-callback) method
Settings are updated with a new field _proxy_. That field has a default value of 
> SOCKS5://127.0.0.1:9050
which is a default address for tor client.
Settings view is updated with new section for Tor and proxy fields.
https://i.ibb.co/mck7Hyg/settings.png
That section also includes **TEST PROXY** button which sends a request to https://ifconfig.co/json and displays information about user's IP.
I haven't worked with Tor before so it would be a good idea for someone who has some experience using tor to test this.

Update tor support with electron proxy

---

src/js/videos.js

Currently FreeTube adds an `https:` to `authorThumbnail` to correct an issue with the Invidious API that was fixed with omarroth/invidious@1fd7ff5. This produces `https:https://yt3.ggpht.com...` which doesn't resolve.

Fix scheme in author thumbnail

---

src/js/templates.js
src/style/player.css
src/templates/player.html

Refers to issue #489
Adds a save icon to give the option to favourite recommended videos suggested below the video player.
Icon is displayed in the top right hand corner following conventions in the rest of the project.
Moved the on click action from the main recommend video div to each element individually to prevent the video playing when the user only wants to favorite it. This is the approach utilised for the video template.
Screenshot showing design changes:

Added save icon to recommended video thumbnails

---

src/renderer/components/ft-list-video/ft-list-video.js

---
'Fix weird published text display on topic videos"
---
Closes issue #541 and #361 
The publishedText in the toLocalePublicationString() function in utils.js is null. This leads to a wrongly used phrase. Now it does not display anything, because the time when uploaded is simply missing.
Before:
After:
**Testing (for fixes that are not easily understandable)**
Tested on the 2pac topic channel
- OS: Windodws
- OS 10
- FreeTube version: Newest release

Fix weird published text display on topic videos

---

static/locales/it.yaml

---
Changed "_API di Indidious_" to "_API di Invidious_"
---
- Bugfix: Typo
https://github.com/FreeTubeApp/FreeTube/issues/559
Just made a correction to "API di Invidious"
- OS: Win10
- FreeTube version: 0.8.0
I hope i didn't messed up anything XD

Fixed typo: "API di Indidious" to "API di Invidious"

---

src/renderer/components/ft-intersection-observer/ft-intersection-observer.js
src/renderer/components/ft-intersection-observer/ft-intersection-observer.vue

---
Creating ft-intersection-observer component
---
N/A
I have created a standalone component to observe viewport intersection. It can observe either itself (most useful for detecting if the user has reached a certain part of the page), or its parent element, controlled by props. It also has props to control standard IntersectionObserver options, as well as an option (defaulting to false) to run its check during the first execution which happens automatically when IntersectionObserver.observe() is called. When an intersection is detected, it emits an 'intersected' event, and emits an …

Creating ft-intersection-observer component

---

package-lock.json
package.json
src/renderer/components/watch-video-comments/watch-video-comments.js
src/renderer/components/watch-video-comments/watch-video-comments.vue

---
Comment sorting and comment day time display
---
https://github.com/FreeTubeApp/FreeTube/projects/3#card-46699030
Sorting was added to the module and now hooked up to Preston's sorting button. Also the bug with the time since comment publish not displaying correctly for days is fixed. The sorting button now also displays the currently selected sorting method.
On a few videos checked again YouTube's website
- OS: Win
- FreeTube version: 0.8

Comment sorting and comment day time display

---

package-lock.json
package.json
src/renderer/components/watch-video-comments/watch-video-comments.js
static/locales/en-US.yaml

---
Fix for infinite comment repeat
---
Closes issue #586 
The module upstream now returns null when no new comments are available. This is now checked before the comment processing and displays a toast message if it is the case.
With the provided video in the issue and a few more videos from the same channel
- OS: Win
- FreeTube version: 0.8

Fix for infinite comment repeat

---

src/renderer/components/distraction-settings/distraction-settings.js
src/renderer/components/distraction-settings/distraction-settings.sass
src/renderer/components/distraction-settings/distraction-settings.vue
src/renderer/components/ft-list-channel/ft-list-channel.js
src/renderer/components/ft-list-channel/ft-list-channel.vue
src/renderer/components/ft-list-video/ft-list-video.js
src/renderer/components/ft-list-video/ft-list-video.vue
src/renderer/components/side-nav/side-nav.js
src/renderer/components/side-nav/side-nav.vue
src/renderer/components/watch-video-comments/watch-video-comments.js
src/renderer/components/watch-video-info/watch-video-info.js
src/renderer/components/watch-video-live-chat/watch-video-live-chat.js
src/renderer/components/watch-video-live-chat/watch-video-live-chat.vue
src/renderer/components/watch-video-recommendations/watch-video-recommendations.js
src/renderer/components/watch-video-recommendations/watch-video-recommendations.vue
src/renderer/store/modules/settings.js
src/renderer/views/Channel/Channel.js
src/renderer/views/Channel/Channel.vue
src/renderer/views/Settings/Settings.js
src/renderer/views/Settings/Settings.vue
src/renderer/views/Watch/Watch.js
static/locales/en-US.yaml

Signed-off-by: Taylor <tayloraviets@gmail.com>
---
Issue #584 "Distraction Free Settings"
---
#584 #590 
This adds a "Distraction Free Settings" section to settings with the following 8 options:
-Hide Video Views
-Hide Video Likes/Dislikes
-Hide Channel Subscribers
-Hide Comment Likes
-Hide Recommended Videos
-Hide Popular Videos
-Hide Trending Videos
-Hide Live Chat
Tested on windows through the UI using the dev_runner script and VS code.
Tested using both the local and invidious player.
Tried to test thoroughly …

PR ready distraction free feature

---

package-lock.json
package.json
src/renderer/components/watch-video-comments/watch-video-comments.js
src/renderer/components/watch-video-comments/watch-video-comments.vue

---
Comment full text & comment link display
---
Issue #581 is closed with this PR.
Previously comment containing links were only displayed up to the first link. This was due to an issue on the scraper module and the internal extraction of comments. I fixed that upstream. Additionally comments and replies now go through the auto linker module in order to display their links in blue and make clickable
Tested on the video where the problem occurred and then on a few other videos
- OS: Win
- FreeTube …

Comment full text & comment link display

---

src/renderer/components/data-settings/data-settings.js

---
Fixed error for importing old subscriptions, which added channels multiple times to profiles
---
Is closing issue #562 
When importing .db files from old FreeTube, a check is performed, to which profiles the channel was added already. If it was added already, then the duplicate addition is skipped
Tested with the file PrestoN provided for me
- OS: Win
- FreeTube version: 0.8

Fixed error for importing old subscriptions, which added channels multiple times to profiles

---

src/renderer/views/Subscriptions/Subscriptions.vue
static/locales/de-DE.yaml
static/locales/en-US.yaml

---
Changed the fixed string 'load more' in the subscription page
---
None
The string in the button 'Load more' on the subscription page was hard coded and not pulled from the yaml files
Tested with English and German.
- OS: Win
- FreeTube version: 0.8

Changed the fixed string 'load more' in the subscription page

---

src/main/index.js
src/renderer/App.js

1. Handle open-url events.
2. Make protocol handling more robust on Win/Linux based on SO post.
3. Change 'ping' message to more descriptive 'openUrl' message.
4. Remove freetube:// protocol in main, and unify URL handling logic.
---
Title
---
Fixes #618.
This fixes the freetube:// links that the Firefox redirect plugin uses on macOS, both when the app is closed and when it is already open.
I've tested this in the above situations on the macOS version below. However the flow for the equivalent functionality in …

Fix freetube:// protocol handling on macOS.

---

src/renderer/components/ft-tooltip/ft-tooltip.css
src/renderer/components/ft-tooltip/ft-tooltip.js
src/renderer/components/ft-tooltip/ft-tooltip.vue

---
Creating ft-tooltip component
---
N/A
I have created a simple tooltip component which can be used to show extra informative text to users when UI space is at a premium.
N/A
The component was tested by placing it in a view and trying all valid position props.
- OS: Linux Xubuntu
- OS Version: 20.04
N/A

Creating ft-tooltip component

---

src/renderer/components/ft-list-video/ft-list-video.js
src/renderer/components/ft-share-button/ft-share-button.js

---
Changes the share YouTube link option to use short YouTu.be links instead
---
[#639 ](https://github.com/FreeTubeApp/FreeTube/issues/639)
Very simply makes a change so that when a video URL is copied it uses the shorter YouTube link instead. Eg. old link: https://www.youtube.com/watch?v=imaginaryURL is now new link: https://youtu.be/imaginaryURL
No visible changes, URL is different now.
Fairly straightforward. 
- OS: Windows
The only note I have on this change is that perhaps people don't always want the …

Use shorter youtu.be links instead of youtube.com for YouTube share links

---

package-lock.json
src/renderer/components/ft-list-video/ft-list-video.js
static/locales/en-US.yaml

---
Add Open/Copy Channel URL to video dropdown
---
#706 
Added an option to copy/open the Channel URL from video dropdown
basic testing for multiple channels. Tested some locales too, shows English text I've added.
- OS: Windows
- FreeTube version: 0.9.1

Add Copy / Open Channel URL to video dropdown

---

src/renderer/components/ft-video-player/ft-video-player.js

---
Added ability to change volume with scroll wheel
---
Fixes #573 
As the title suggests, I was finally able to figure out how to enable volume scroll on hover. Now, when the user hovers over the volume panel the user can change the volume with a wheel scroll. 
- OS Version: 1909
Sorry for the re-post.

Added ability to change volume with scroll wheel

---

src/renderer/components/ft-video-player/ft-video-player.js

---
Added selection of resolution > 1080p for all devices.
---
Resolutions higher than 1080p that have a mp4 file available can be selected even on monitors with less resolution. 
- OS: Win
- FreeTube version: 0.9.1 Nightly
Sometimes the player stutters due to the immense amount of data. E.g. when playing 8k

Added selection of resolution > 1080p for all devices.

---

src/renderer/views/Watch/Watch.js

---
Changed Title of Watch view 
---
Fixes #702 
I have changed the title of the Watch view from the generic "Watch - FreeTube" to now show the title of the video instead
- OS Version: 1909
I wasn't sure exactly where to call my updateTitle function. I decided to call it in addToHistory because 
that will get called once for every video. Let me know if you have a better spot for it or want me to change anything.

Changed title of Watch view to title of the video

---

package-lock.json
package.json

---
Error handling update of comment scraper
---
A contributor added proper error handling to the comment extraction, which should prevent the extraction from erroring out after the HTML is converted to JSON.
Yes on a few videos in only the module but also in the dev mode in FreeTube
- OS: Win
- FreeTube version: 0.92

Error handling update of comment scraper

---

src/renderer/components/ft-video-player/ft-video-player.js

---
Implement frame by frame advance using keyboard shortcuts
---
#730 
Enables advancing and returning to the next or previous frame by pressing Z or X, respectively.
Open a video and press Z or X to move ahead or behind one frame.
Tested on both local and Invidious APIs, resolutions equal and above 720p and those below, dash and legacy file formats, on videos without a 60fps option for higher resolutions and those with it.
**Desktop**
- OS: Artix
- OS Version: N/A
- FreeTube version: v0.9.2
I …

Implement frame by frame advance using keyboard shortcuts

---

src/renderer/components/ft-share-button/ft-share-button.js
src/renderer/views/Trending/Trending.js

---
Fixing wrong url parameter for YouTube video links with timestamp
---
Closes issue #784 
The code checks if a '?' is already in the URL, so another URL parameter is already available. If not, then the '&' which is usually used for timestamps is swapped with a '?' to make the URL valid.

Fixing wrong url parameter for YouTube video links with timestamp

---

package-lock.json
package.json
src/renderer/components/ft-video-player/ft-video-player.js
src/renderer/videoJS.css

---
Title of video in full screen
---
Closes #694 
This PR adds an overlay to the application that displays the title of the video. For it to work, the app must be in full screen mode and it will active when you move the mouse. The overlay will hide itself when the `userinactive` event happens from the controlBar.
- OS Version: 1909
I am stuck on the last step. I am unable to manipulate the css for the overlay. I want to make the font larger and for the container it's in to span the top of the screen instead of causing the title to wrap underneath with bigger titles. I have tried putting the css for it inline in the `.vue` file as well as the `content` …

Closes: Title of vid in fullscreen

---

.gitignore
src/renderer/components/data-settings/data-settings.js

---
Added check for duplicate in YouTube JSON file
---
Closes issue #844 
The code did not check whether duplicates in the file itself existed. This lead to duplicates from YouTube's side to slide through
Tested with a manipulated JSON file which had multiple entries duplicates
- OS: Win
- FreeTube version: v10.0.0

Added check for duplicate in YouTube JSON file

---

src/renderer/views/Watch/Watch.js

---
Fix 0 (dis)likes displayed as NaN
--
Closes #897 
It simply checks whether the value of likes and dislikes from ytdl-core is NaN, which means it is 0 on the webpage and if so replaces it with 0
Tested on a few videos with 0 likes and dislikes
- OS: Windows
- FreeTube version: v10.0.0

Fix 0 (dis)likes displayed as NaN

---

src/renderer/components/ft-input/ft-input.vue
src/renderer/components/ft-toggle-switch/ft-toggle-switch.vue
src/renderer/components/ft-tooltip/ft-tooltip.css
src/renderer/components/ft-tooltip/ft-tooltip.js

---
Fixed the improper position of a few Tooltip components on the Settings page
---
#794 
This fixes theimproper position of Tooptip on the Settings page with some added extra styles and positions.
Yes.
- OS: Windows
- FreeTube version: latest

Fixed tooltip position

---

src/renderer/components/data-settings/data-settings.js

---
Fix OPML import issue
---
Fixes https://github.com/FreeTubeApp/FreeTube/issues/962
FreeTubes dependencies were updated a few days ago. The library `opml-to-json` was also updated, but it had breaking changes. These changes now causes the opml import to break without an error message (in the interface). This PR implements the suggested changes from `opml-to-json`.  
https://github.com/azu/opml-to-json/releases/tag/v1.0.0
Has this pull request been tested? Yes.
Please describe shortly how you tested it and whether …

Fix OPML import issue

---

src/renderer/components/ft-input/ft-input.css
src/renderer/components/ft-input/ft-input.js
src/renderer/components/ft-input/ft-input.vue

---
Autofill Searchbar
---
Implements #840 
This pull request allows to autofill the search bar when navigating with arrow keys.
1. Searching 
2. Navigating using arrow keys
3. Continue typing in search bar
Tested manually by trying different inputs in search box.
- OS: Pop OS 
- OS Version: 20.10
- FreeTube version: v0.9.3 Beta
Originally, search suggestions were shown in HTML5 `<datalist>`, since `<option>` …

Autofill Searchbar

---

src/main/index.js
src/renderer/App.js

---
Changed command line input to only allows youtube video links.
---
#955 
#1020 
Instances of Freetube running through app.asar have extra arguments in the command line which were being mistaken as search terms. Hoping that this is a infrequently used feature and at Preston's tentative suggestion, anything that isn't a youtube link is discarded from the command line input.
- OS: Artix
- OS Version: N/A
- FreeTube version: 0.11.3 (commit b37fab46227198af7977a574dafe5f988b21c0c2)

Changed command line input to only allows youtube video links.

---

_scripts/build.js
package.json

---
Title
---
- [ X] Feature Implementation
armv7l build support
npm run build:arm32 for armv7l
npm run build:arm64 for aarch64

Add build support for armv7l

---

src/renderer/components/distraction-settings/distraction-settings.js
src/renderer/components/distraction-settings/distraction-settings.vue
src/renderer/components/side-nav/side-nav.js
src/renderer/components/side-nav/side-nav.vue
src/renderer/store/modules/settings.js
static/locales/en-US.yaml

---
Added ability to hide Playlists
---
#952 
Right in "Distraction Settings" there's no toggle to show/hide side-bar playlists, so this pr adds ability to show/hide playlists
hide Playlists
- OS: Windows
- FreeTube version: 0.11.1

feat: added ability to hide Playlists

---

src/renderer/components/side-nav-more-options/side-nav-more-options.vue
static/locales/en-US.yaml

---
Translated menu option(small screen)
---
#793 
Before this menu for "more" options wasn't able to translate to other languages, this PR replaces the hard-coded strings to vue-i18n strings "$t()".
- OS: Windows
- FreeTube version: 0.11.1

fix: translated menu("more" option on small screen)

---

src/renderer/components/player-settings/player-settings.js
src/renderer/components/player-settings/player-settings.vue
src/renderer/store/modules/settings.js
src/renderer/views/Watch/Watch.js
static/locales/en-US.yaml

---
added playlist next video interval option
---
#971 
This pull adds the feature to control the playing next next video interval in the playlist, currently it has only 5 seconds, this PR brings the control from 0 to 60 secs.
- OS: Windows 
- FreeTube version: 0.11.2
I added string as "Playlist next video interval", because to avoid confusion.

added playlist next video interval setting

---

static/locales/en-US.yaml

---
Minor typographical typo in en-US.yaml
---
Would close #1031
This fixes a typographical typo (from "it's" to "its"); this is in the description of "Fetch Feeds from RSS" toggle button (when you hover your cursor over the circled question mark)
What currently looks like: 
(I don't have any after screenshots.)
N/A (untested, though this is typographical and not code related)
- OS: Manjaro Linux
- OS Version: 20.2.1
- FreeTube version: 0.11.2 Beta
N/A

Minor typographical typo in en-US.yaml

---

src/renderer/components/watch-video-description/watch-video-description.js

When pulling video information from Invidious, hashtag-related links present in the description need to be replaced with valid links.
In this case, a freetube:// link was deemed the most appropriate.
Fixes #932

Replace '/hashtag' refs with freetube:// links

---

src/renderer/App.js
src/renderer/components/top-nav/top-nav.js
src/renderer/store/modules/utils.js
src/renderer/views/Watch/Watch.js

Closes #982 (couldn't find any other related issue)
This allows users to specify the timestamp of a video (in seconds)
- by inputting a link into the search bar
- by making use of the protocol link (freetube://), p.e in a browser
**Testing**
Manually tested
**Desktop:**
- OS: W10

Support for the 't' parameter in links

---

src/renderer/components/watch-video-live-chat/watch-video-live-chat.js

---
Fixed large custom emotes in live chats
---
#1116
Custom emotes are loaded as images. The problem was that these images are 64x64 in size by default, so they are huge compared to the default emojis and text size. I toned them down in the corresponding html element
Before:
After:
Has been tested on a few live streams.
- OS: Win
- FreeTube version: v12.0.0
Custom setting to …

Fixed large custom emotes in live chats

---

src/renderer/store/modules/ytdl.js

---
Added fix for wrongly applied publishedText template
---
Closes issue #1094 
Problem was that ytdl-core module was called with the selected language of the user. While this works great in theory to give everyone the translation right from YouTube, it creates new and massive overhead. The problem is that all other modules that return strings to display from YouTube, do not allow the selection of languages, so for some correctly translated strings will be returned automatically while others need a translation. Now it is forced that every string needs a translation or will be English otherwise.
Has this pull …

Added fix for wrongly applied publishedText template

---

src/renderer/components/watch-video-comments/watch-video-comments.css
src/renderer/components/watch-video-comments/watch-video-comments.js
src/renderer/components/watch-video-comments/watch-video-comments.vue

---
Reimplementation of goToChannel from PR 850
---
#782 
Unfortunately #850 did not update the PR and now some of the redirections do not work anymore after multiple updates.
Therefore this PR implements #850 and the suggestion made as well as the new and correct redirection to comment channels
Tested with Invidious and Local API
- OS: Windows
- FreeTube version: v12.0.0

Reimplementation of goToChannel from PR 850

---

src/renderer/components/privacy-settings/privacy-settings.js
src/renderer/components/privacy-settings/privacy-settings.vue
src/renderer/store/modules/settings.js
src/renderer/views/Watch/Watch.js
static/locales/en-US.yaml

---
Video meta file removal option
---
The user now has the option to automatically delete all storyboard and DASH files from a video when the view is closed. The setting is especially useful for debugging purposes, but by default reduces the memory footprint of the application.
Tested with different videos and different route changes.
- OS: Windows
- FreeTube version: 12.0.0

Video meta file removal option

---

package-lock.json
package.json

---
Bumped yt-comment-scraper version
---
Published a new module version which supports the setCookie flag with the new cookie that is needed, but also keeps freetube comments running.
Tested on a new vm
- OS: Windows
- FreeTube version: v12.0.0

Bumped yt-comment-scraper version

---

src/renderer/App.js
src/renderer/components/watch-video-comments/watch-video-comments.vue
src/renderer/components/watch-video-description/watch-video-description.js

Closes #811
This PR makes it so certain YouTube links present in user related data (e.g. description of a video) open the appropriate view in the app when clicked.
This has been implement for video, playlist, search and channel URL types.
**Testing**
Fully tested
**Desktop:**
- FreeTube version: development
TODO?
- Handle a certain amount of URL shortening services (but I'm not sure I wanna go down that rabbit hole... if I do, I'll do so in a future PR)

Link app views to related YouTube url navigations

---

src/renderer/components/data-settings/data-settings.js
src/renderer/components/ft-list-video/ft-list-video.js

---
Fix for missing import of marked as watched videos & publish date displayed
---
Closes issue #1173 
During import videos with 2 missing keys are now allowed in as well, because they are the missing description and view count from videos added through the 'Mark as watched' when using RSS.
Additionally videos marked as watched are now also showing the publishing date in history
Tested with exported histories.

Fix for missing import of marked as watched videos & publish date displayed

---

_scripts/build.js

---
fix arm32 building
---
was
```javascript
if (args[3] === 'arm32') {
arch = Arch.armv7l
}
```
instead of
```javascript
if (args[2] === 'arm32') {
arch = Arch.armv7l
}
```
**Testing**
I have tested this fix.
- OS: Ubuntu Linux
- OS Version: 20.04 lts
- FreeTube version: 0.12

fix arm32 building

---

src/renderer/components/ft-video-player/ft-video-player.js
src/renderer/videoJS.css

https://github.com/FreeTubeApp/FreeTube/issues/1178
This PR makes the player hide "Full Window" button when in full screen mode
Before
After
- View a video
- Enter full screen mode
- Ensure full window button hidden
- OS: MacOS
- FreeTube version: 12.0.0 (latest on `development` actually)

* Update player to hide full window button when in full screen mode

---

src/renderer/components/watch-video-info/watch-video-info.vue

https://github.com/FreeTubeApp/FreeTube/issues/1180
Update "toggle theatre mode" button icon to [`tv`](https://fontawesome.com/icons/tv?style=solid)
- View a video
- Check button icon
- OS: MacOS
- FreeTube version: 12.0.0 (latest on `development` actually)

* Update "toggle theatre mode" button icon

---

src/renderer/components/ft-button/ft-button.css
src/renderer/components/ft-list-video/ft-list-video.vue
src/renderer/components/side-nav/side-nav.vue
src/renderer/components/top-nav/top-nav.vue

#375
- removes `outline: none` from buttons forcing keyboard focus outline to be hidden
- adds `tabindex="-1"` for thumb in video list, preventing lengthy navigation with tab
- adds `tabindex="0"`, `role="button"` and `@keypress` handler for buttons which are actually divs
This greatly improve keyboard navigation, making it possible to use FreeTube without pointer.

feat: better keyboard navigation, fix #375

---

src/renderer/App.js
src/renderer/components/top-nav/top-nav.js
src/renderer/store/modules/utils.js

https://github.com/FreeTubeApp/FreeTube/issues/1218
This PR makes channel URL input in search input box in top nav handled by redirecting to channel view.
Instead of searching with it
Channel URL expected to be like `/channel/{channelID}`
https://user-images.githubusercontent.com/1018543/115644811-c48a2b80-a351-11eb-9504-39f0982c24b8.mp4
- Enter channel URL (e.g. https://www.youtube.com/channel/UCkRfArvrzheW2E7b6SVT7vQ)
- Press Enter/"Go To" button
- Ensure channel view shown instead of search result view
- OS: MacOS
- OS …

* Update top nav search input to direct to channel panel when channel URL provided

---

src/main/index.js

Follow up change for #1153
In #1153 some settings change does not apply on all opened windows
This PR's change would ensure the following settings are applied to all opened windows
- smooth scrolling enabled (by closing all opened windows instead of just the "main" window)
- proxy URL (by applying the proxy setting to all opened windows instead of just the "main" window)
(Not Applicable)
"Smooth scrolling": opening multiple windows via the button introduced in #1153, update "smooth scrolling enabled", all windows are closed and a new window reopened
"Proxy URL": NOT tested (No …

* Update main process to handle all opened windows on some setting change

---

src/renderer/components/general-settings/general-settings.js
src/renderer/main.js

---
---
#1205 
- New locale option created
- Option sets the local to the same local that the system running freetube is using  
- Option is the new standard Locale Preference 
- Option only shows up in case of a supported system locale if the system locale is not support `en-US` gets set 
I tested it with system locale: English(US) `en-US.yaml` most of the time and it works fine. But if I change to just English without (US) it tries to access `en.yaml`, which is not existing. Same would be for `fr-FR`, `de-DE`. For `pt-Pt` and `pt` it should be working fine, because there is a  `pt.yaml` file. 
Maybe something for a new Issue or for this Issue #673
- OS: Manjaro Linux 
- OS Version: 21.0.3
- FreeTube version: 7.11.1
**Feel free to correct the code :D**

Adding a 'Follow System' option to the 'Locale Preference'

---

package-lock.json
package.json
src/renderer/components/ft-video-player/ft-video-player.js
src/renderer/components/sponsor-block-settings/sponsor-block-settings.css
src/renderer/components/sponsor-block-settings/sponsor-block-settings.js
src/renderer/components/sponsor-block-settings/sponsor-block-settings.vue
src/renderer/store/modules/settings.js
src/renderer/store/modules/sponsorblock.js
src/renderer/views/Settings/Settings.js
src/renderer/views/Settings/Settings.vue
src/renderer/views/Watch/Watch.vue
static/locales/en-US.yaml

---
SponsorBlock
---
Fixes #798 
Simple implementation of SponsorBlock.
- added SponsorBlock section in settings with enable toggle and api url
- sponsor segments are marked on video timeline
- I observe on [timeupdate](https://docs.videojs.com/player#event:timeupdate) event. If currentTime is within some sponsor segment I jump to the end of this segment.
- colors from https://github.com/polymorphicshade/NewPipe/blob/b1faacc4a9070bde4686f016fd4cf530b412e3f6/app/src/main/res/values/colors.xml#L86-L92 (GPLv3)
Settings section
Skipped sponsor segments are green
- OS: Linux Mint
- OS Version: 20.1 …

SponsorBlock

---

src/renderer/views/Trending/Trending.js

---
Fixed old trending page api call
---
Closes #1295 
When the trending page module was updated, the api call was not adjusted to the new api
Has been tested for japanese and us american trends
- OS: Windows
- FreeTube version: v13.0.0

Fixed old trending page api call

---

src/renderer/components/watch-video-comments/watch-video-comments.css
src/renderer/components/watch-video-comments/watch-video-comments.vue

---
Fix wrongly sized comment channel links, Added links to comment reply channels
---
#1286 
I added a new span element around the comment author's name, which now has registers the click event and changes the cursor to pointer, instead of the whole <p> line. Same goes for comments.
Additionally I added the click event to comment replies, with the reply.authorLink, so you can now go to the channel of comment replies.
Tested on a few videos with normal comments and replies. …

Fix wrongly sized comment channel links, Added links to comment reply channels

---

src/renderer/components/data-settings/data-settings.js

---
Fixed Importing subscriptions from NewPipe when subscribed to channels on other services
---
closes #1304 
I added a filter to NewPipe subscriptions to exclude subscriptions from services that aren't YouTube (ex. BandCamp)
Yes.
I built it and was able to import from NewPipe successfully when subscribed to channels from other services.
**Desktop (please complete the following …

Fixed Importing subscriptions from NewPipe when subscribed to channels on other services

---

src/renderer/App.js
src/renderer/components/ft-share-button/ft-share-button.js
src/renderer/components/ft-share-button/ft-share-button.vue
src/renderer/components/watch-video-info/watch-video-info.js
src/renderer/components/watch-video-info/watch-video-info.vue
src/renderer/views/Watch/Watch.vue

None
Update Video Info Panel -> Share Button -> Youtube Side -> "Open Link" button
To open webpage for current video **with** active playlist if there is one in FreeTube
Just screenshot for specifying the button updated
Test case A (video without playlist):
- Input URL https://www.youtube.com/watch?v=eBZ2vA9D2RA into FT
- Press "Open Link" button
- Inspect URL
Test case B (video with playlist):
- Input URL https://www.youtube.com/playlist?list=PLzFTGYa_evXiOHCB_cb1Sqsk-LIARmLgd into FT
- View one of videos
- Press "Open Link" button
- Inspect URL
**Desktop (please complete the …

Update "Open Link" button to include playlist ID

---

src/renderer/App.js
src/renderer/components/ft-search-filters/ft-search-filters.js
src/renderer/components/top-nav/top-nav.js
src/renderer/components/top-nav/top-nav.sass
src/renderer/components/top-nav/top-nav.vue

#1251 
When search filter is updated and value is different from default
Update UI to indicate that
Actual effect to be decided
- Open filter panel
- Change any filter from default value and back
- Observe visual change
- OS: MacOS
- FreeTube version: 12.0.0 (latest on `development` actually)

Implement search filter changed indicator

---

src/renderer/components/ft-video-player/ft-video-player.js

#347
Remove the big play button shown when video paused
https://user-images.githubusercontent.com/1018543/117793853-3c77b180-b27f-11eb-9d62-da45da7c267d.mp4
- Play a video
- Pause it
- Check for the big play button
- OS: MacOS
- FreeTube version: 12.0.0 (latest on `development` actually)

Update video player to remove default big play button shown when paused

---

src/renderer/App.js
src/renderer/components/ft-share-button/ft-share-button.js
src/renderer/components/top-nav/top-nav.js
src/renderer/components/watch-video-info/watch-video-info.js
src/renderer/store/modules/utils.js

None
Update Youtube URL handling to recongnize playlist ID in URL
Only for format of `https://www.youtube.com/watch?v=vid&list=lid`
Test case A (video without playlist):
- Input URL https://www.youtube.com/watch?v=eBZ2vA9D2RA into FT
- Inspect playlist panel
Test case B (video with playlist):
- Input URL https://www.youtube.com/watch?v=eBZ2vA9D2RA&list=PLzFTGYa_evXiOHCB_cb1Sqsk-LIARmLgd&index=51 into FT
- Inspect playlist panel
- OS: MacOS
- OS Version: …

Update Youtube URL handling to recongnize playlist ID in URL

---

src/renderer/components/ft-video-player/ft-video-player.js

#1328
After change, muting video via mute button would save the mute state to next video
Too lazy
But you want video instead of testing I can make one :P
- Open a video
- Mute it via mute button
- Play next video (in playlist or recommended or autoplay)
- Ensure the new video also muted
- OS: MacOS

Fix volume in session not persisted probably when muted

---

src/renderer/components/side-nav-more-options/side-nav-more-options.js
src/renderer/components/side-nav-more-options/side-nav-more-options.vue

---
Hide trending and most popular when set to hidden (Portrait Mode)
---
closes #1291 
When you make your screen smaller, trending and most popular won't display if you disable them in settings.
Before (Trending & Most Popular set to hidden):
After  (Trending & Most Popular set to hidden):
Yes
- OS: Windows
- OS Version: Windows 10
- FreeTube version: 0.13

Hide trending and most popular when set to hidden (Portrait Mode)

---

src/renderer/components/playlist-info/playlist-info.css
src/renderer/components/playlist-info/playlist-info.js
src/renderer/components/playlist-info/playlist-info.vue
src/renderer/views/Playlist/Playlist.js

#1340
Update playlist page thumbnail to start playing first video on click
https://user-images.githubusercontent.com/1018543/119954006-26812500-bfd1-11eb-83b2-635531b85ee9.mp4
- Open a playlist
- Click on thumbnail
- OS: MacOS

Update playlist page thumbnail to start playing first video on click

---

src/renderer/components/ft-input/ft-input.js
src/renderer/components/ft-input/ft-input.vue
src/renderer/components/top-nav/top-nav.vue

#1317 
Update top nav search input to disable spellcheck
- Enter `joyner` into top nav search input
- OS: MacOS

Update top nav search input to disable spellcheck

---

src/renderer/components/ft-search-filters/ft-search-filters.css
src/renderer/components/ft-search-filters/ft-search-filters.vue

#1337
Update search filter style so it's smaller in size and has 10% transparency
https://user-images.githubusercontent.com/1018543/119937349-32fb8280-bfbd-11eb-84b6-188895103df4.mp4
- Open filter
- Keep resizing the window
- OS: MacOS

Improve search filter appearance

---

static/external-player-map.json

---
Add command line argument mapping for the VLC player
---
#418 
This PR adds command line argument mapping for the VLC player.
- Opening videos
- Opening videos at a specified start offset
- Opening videos with different playback rates
- OS: Windows
- FreeTube version: 0.13.1 Beta
VLC doesn't seem to have support for YouTube playlists out-of-the-box.
While I did add flags for  playlist shuffle/reverse, they are essentially useless, since opening playlists isn't supported.
Just wanted to note this here.

Add command line argument mapping for the VLC player

---

src/renderer/store/modules/utils.js

---
Recognize YT short links in search & for external apps
---
closes #1604
This PR adds a shorts endpoint to the "getVideoParamsFromUrl" method
Search "https://youtube.com/shorts/MS82yTaKRjQ?feature=share" without using this PR (no search results)
Search "https://youtube.com/shorts/MS82yTaKRjQ?feature=share" while using this PR (video loads)
**Desktop (please complete the following …

Fix: Recognize YT short links in search & for external apps

---

src/renderer/components/ft-video-player/ft-video-player.js

---
Fixes wrong variable name
---
N/A
Fixes wrong variable name defaultTheatreModeActive to defaultTheatreMode. This bug resulted in the "enable theatre mode" icon being shown when theatre mode was set to active by default in the settings (which should have and now appropriately shows the icon for disabling theatre mode).
- OS: OpenSUSE

Fixes wrong variable name

---

src/renderer/components/ft-video-player/ft-video-player.js

---
Theater mode icon behavior fix
---
N/A
The last silly fix for the theater mode icon. Thirty minutes ago, I just realized (and read under #1236) that theater mode's state when switching between videos is its last known state rather than the default setting. The icon was wrongly being determined by the default setting. My bad!
- OS: OpenSUSE

Theater mode icon behavior fix

---

src/renderer/App.css
src/renderer/App.vue

---
Allow large changelogs to scroll
---
N/A
Fixes the changelog message -- you know, the one that pops up when there is a new release out -- to scroll when there is a sizable enough amount of text.
Before:
After:
- OS: OpenSUSE
This pull request about large changelogs is, of course, just a spontaneous fix & is completely unrelated to anything. 😉

Allow large changelog messages to scroll

---

src/renderer/components/side-nav-more-options/side-nav-more-options.vue

---
fix trending text in small window
---
Please link the issue your pull request is referring to.
None
Side-nav-more-options wasn't updated in #1483 so the trending text wasn't displaying properly in small window
Yes, I ran the application and checked that the trending string was …

fixes: trending text in small window

---

src/renderer/components/ft-video-player/ft-video-player.js

---
Fixes video volume scroll from activating in mediaplayer menus
---
#1643 
Prevents menus on the mediaplayer (e.g., video quality level selection, caption settings, playback rate) from being unable to be scrolled through when "Scroll Volume Over Video Player" is active. Now, the volume does not change when scrolling over a menu on the mediaplayer, and the menus can be scrolled through with ease.
Tested scrolling on video quality level selection, caption settings, and playback rate menus while the setting was active.
- OS: OpenSUSE
- OS Version: …

Fixes video volume scroll from activating in mediaplayer menus

---

src/renderer/sass-partials/_ft-list-item.sass

---
Fixes thumbnail width
---
Closes #1641
Fixes the thumbnail width in listed videos from 231px to 250px.
Tested on dev and a linux-unpacked build. Checked video thumbnails on subscription page, recommended videos, channel videos, and playlist videos.
- OS: OpenSUSE
- FreeTube version: v0.14.0
Thanks to @ChunkyProgrammer for this unforgettable tip: `npm install` before you test code, write code, or push code!!

Fixes thumbnail width

---

src/renderer/components/ft-input/ft-input.css
src/renderer/components/ft-input/ft-input.js
src/renderer/components/ft-input/ft-input.vue
src/renderer/components/top-nav/top-nav.vue
static/locales/en-US.yaml

Closes #1387
Update top nav search to add clear search input text button
Also update the padding of input text box so that input text won't appear under the "arrow-right" button
https://user-images.githubusercontent.com/1018543/120764623-ebd83900-c54a-11eb-95da-a50112ef01a7.mp4
- Enter text very long into input text box
- Press the new button
- OS: MacOS

* Improve style of top nav search input

---

src/renderer/components/playlist-info/playlist-info.js

Fixes #1351
When copying the link of a playlist FreeTube doesn't show any feedback to the user that the link has been copied like it does when copying a video URL. This PR makes it show the "URL copied to clipboard" message when copying playlist links.
Before
https://user-images.githubusercontent.com/73130443/119911710-5ab10300-bf49-11eb-9435-b2104ce6f06c.mp4
After
https://user-images.githubusercontent.com/82644961/132214284-d6db1b65-c554-4cb0-ab9c-914a178139f8.mp4
- OS: Arch Linux
- FreeTube version: Based on be58077

Feedback when copying playlist link

---

src/renderer/App.js
src/renderer/components/top-nav/top-nav.js

https://github.com/FreeTubeApp/FreeTube/issues/1337#issuecomment-869738146
As title
https://user-images.githubusercontent.com/1018543/123768697-22f7fb00-d8fb-11eb-9143-a35da6ae5350.mp4
Open app, open filter, go to another page
- OS: MacOS
- FreeTube version: latest on `development`

Update app to hide top nav filter panel on page change

---

README.md
src/renderer/components/data-settings/data-settings.vue
src/renderer/views/About/About.js

---
Replaces outdated links to FreeTube GH wiki
---
N/A
Replaces links to the now-deprecated FreeTube GitHub wiki with links to our docs site, https://docs.freetubeapp.io.
- OS: OpenSUSE

Replaces outdated links to FreeTube GH wiki

---

src/renderer/components/ft-video-player/ft-video-player.js

---
Theatre Toggle Keybind
---
Closes #814 
Adds the required lines for a "Toggle Theatre Mode" bound to [T]
N/A
Repeatedly pressed the keybind on four different videos 
- OS: Arch Linux
- OS Version: 5.14
- FreeTube version: 14.0 Beta
N/A

Add Toggle Theatre Keybind [T]

---

src/renderer/components/ft-video-player/ft-video-player.js

---
feat: Optimize caption sort order
---
Closes #1444
This PR will place captions with a matching locale (language +country) at the top (full string ex: english (United States)) followed by locales for the same language (ex: English(United Kingdom), English (Canada) ) then locales for that language that are auto-generated (ex: English (auto-generated) ) and finally it will go alphabetically (ex: Albanian)
The [example video](https://www.youtube.com/watch?v=r1bUcNeyMpM) (provided by in the issue) will look like this: 
German as selected language:
English (GB) as …

feat: Optimize caption sort order

---

src/renderer/components/watch-video-comments/watch-video-comments.css
src/renderer/components/watch-video-comments/watch-video-comments.js

---
Fixes comment formatting
---
closes #1588
Fixes line breaks in comments & replies not being rendered properly. This problem was caused from 1. a missing style and 2. `<br>` characters wrongly being removed from #1342. It is worth noting that this problem had always existed because of point number 1, so #1342 is not to blame for this bug's existence ([verified by this older build](https://github.com/FreeTubeApp/FreeTube/actions/runs/1041348454)).
- OS: OpenSUSE
Did not have to do this for live chat because line …

Fixes comment formatting

---

src/renderer/views/Channel/Channel.css
src/renderer/views/Trending/Trending.css

---
Style improvements to Channel & Trending pages
---
closes #1733
*Bug fix:* Adds 10px margin between between Channel info section & channel banner.
*Additional improvements:* 
- Removes :focus styling for unintended effects with auto-focusing on Trending page. 
- Replaces underline with bold text weight & primary color bottom border on selected/active tab. 
- Replaces animated background color change with bold text weight on tab:hover. 
- Changes inactive tabs' color to tertiary text color. 
- Removes unnecessary margin beneath tabs. 
- Removes some of the empty vertical space on Channel top section. 
_Before:_
_After:_ …

Style improvements to Channel & Trending pages

---

_scripts/webpack.renderer.config.js
_scripts/webpack.web.config.js
_scripts/webpack.workers.config.js

N/A
Update webpack config to remove explicit HMR plugin
This change suppresses warning
"<w> [webpack-dev-server] "hot: true" automatically applies HMR plugin, you don't have to add it manually to your webpack configuration."
N/A
- Run app via `npm run debug`
- Change any renderer component related code (visible condition/style/class name)
- See running app renders according to updated code without restart
- OS: MacOS
- OS Version: 11.6
- FreeTube version: Git SHA f69e55342cfb507cb83a6c16f07267eae0ec425e
**Additional …

Update webpack config to remove explicit HMR plugin

---

src/renderer/components/ft-input/ft-input.css
src/renderer/components/ft-input/ft-input.js
src/renderer/components/ft-input/ft-input.vue

#1387
Missing change for #1392
Update text input box to focus on text input element after "reset button" clicked
https://user-images.githubusercontent.com/1018543/132451601-ee44e74b-d7ff-4226-a7fd-42c7e4e239e0.mov
- Type something
- Press reset button
- OS: MacOS
- OS Version: 11.5.2
- FreeTube version: based on 4a871578bfb468ddae152147f3f40d1788c2a4ec

Focus in input after text clear

---

_scripts/dev-runner.js
src/renderer/views/Watch/Watch.js

Closes #1627
Fix infinite reloading issue when trying to watch a watched video
This seems to be caused by having an existing matching file in `dashFiles` or `storyboards`
Removing `static/dashFiles` & `static/storyboards` once manually is still required after this change is introduced.
https://user-images.githubusercontent.com/1018543/132454627-8e41cbe0-fe6a-4705-bcd4-80ddd4fdbe30.mov
- Checkout source code
- `npm ci`
- `npm run debug`
- Go Trending
- Pick a video to watch
- Go Trending again
- Pick the same video to watch …

Fix watching video in development

---

src/renderer/components/external-player-settings/external-player-settings.vue
src/renderer/components/ft-input/ft-input.css
src/renderer/components/ft-input/ft-input.js
src/renderer/components/ft-input/ft-input.vue
src/renderer/components/ft-profile-edit/ft-profile-edit.vue
src/renderer/components/general-settings/general-settings.vue
src/renderer/components/proxy-settings/proxy-settings.vue
src/renderer/components/sponsor-block-settings/sponsor-block-settings.vue

It's [a comment/feedback in another PR](https://github.com/FreeTubeApp/FreeTube/pull/1669#issuecomment-918015016)
Before: Top nav input box action button icon is always "arrow right"
After: Action button icon changes depend on input text "looks like a youtube URL" or not
- Initial: icon = "search"
- Looks like YT URL: icon = "arrow right"
- Otherwise: icon = "search"
Also implements
["Having the disappear animation of the Clear Text button also occur on appear/re-appear for visual consistency."](https://github.com/FreeTubeApp/FreeTube/pull/1669#issuecomment-924003650)
Icon change:
Button animation change: …

Update top nav input box action button icon depends on input

---

src/renderer/components/watch-video-comments/watch-video-comments.css

Fixes #1851
Prevents commenter's username and comment content from overflowing the container.
Before:
After:
Use dev tools to replace username and comment content with a long word.
- OS: Debian
- FreeTube version: 0.15.0
None.

Prevent comments from overflowing their container

---

src/renderer/views/UserPlaylists/UserPlaylists.js

closes #1507
Update user fav list view (by playlists on sidebar) to NOT have scroll to top effect when "load more" is pressed.
The code is temporarily changed to load 5 per batch for easier testing
https://user-images.githubusercontent.com/1018543/138631307-a28be726-c5f9-4856-88db-18e2754df5c2.mov
- Add many videos to fav
- Press "Load more"
- OS: MacOS
- OS Version: 11.6
- FreeTube version: based on 8f3f4adcf3a562ad9c570e8716b7b6b00ee37654

! Fix user fav list having "scroll to top" effect when "load more" clicked

---

package.json
src/main/index.js
yarn.lock

- We need to wait for https://github.com/electron/electron/issues/31448 to be fixed before merging this PR
Closes #1640
Closes #1651
Closes #1763 
Upgrade electron 13.x > 15.x AND fix the issue caused by a breaking change in electron 14
Breaking change:
https://github.com/electron/electron/pull/28550
Child windows no longer inherit BrowserWindow construction options from their parents.
Nothing visible should really changed
All Dev team members should test this in
- Multiple OS
- Dev version (`npm run dev`) and built version afterward (can trigger nightly build manually) …

Upgrade electron from 13 to 15

---

src/renderer/components/ft-video-player/ft-video-player.js

---
Select current playback rate in video player playback rate selector
---
Closes: https://github.com/FreeTubeApp/FreeTube/issues/1273
Related to: #1274
Related to: #1745
This pull request ensures that the currently selected playback speed is always visible in the list of playback speeds. It also works if the playback speed is between two of the selectable values which is likely to occur if you use the CTRL + scroll setting in #1745, in which case it will scroll to the next lowest value. A previous pull request #1274, which wasn't merged, implemented scrolling right to the bottom …

Select current playback rate in playback rate selector

---

src/renderer/components/watch-video-info/watch-video-info.js

---
Fix: parsing video info of videos with like count disabled
---
closes #1911 
It will change the like/dislike count to '0' if likes/ dislikes are disabled
Yes
- OS: Windows
- OS 10
- FreeTube version:  Latest Nightly

Fix: parsing video info of videos with like count disabled

---

src/renderer/components/ft-input/ft-input.css

---
Fix long single worded search suggestions leaving suggestion box container
---
closes #1769
This fixes the issue where a very long single word search suggestion e.g. (abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz) visually doesn't stay within the suggestion box. …

Fix long single worded search suggestions leaving suggestion box container

---

src/renderer/components/playlist-info/playlist-info.js
src/renderer/components/playlist-info/playlist-info.vue

---
Hide playlist views on playlist summary screen
---
closes #1905 
Hides playlist views on playlist summary screen
Has this pull request been tested? Yes, locally
- OS: [Windows]
- OS Version: [10]
- FreeTube version: [0.15.1]

added logic to hide playlist views

---

src/renderer/components/watch-video-comments/watch-video-comments.vue

---
Title
---
Closes #1906
https://github.com/FreeTubeApp/FreeTube/issues/1906
The PR wraps the font thumbs-up icons in the comments section in a v-if that checks if the hideCommentLikes is disabled.
***BEFORE***
***AFTER***
I ran it before and after and observed …

Hiding thumbs-up icon when the hide Comment Likes setting is enabled

---

src/renderer/videoJS.css

---
Title
---
Closes #2077 
Fixes thumbnail being obstructed by time tooltip by moving the thumbnail up.
Before:
After:
**Testing**
Has this pull request been tested? Yes
UI scale works fine after the patch.
**Desktop:**
- OS: [Fedora Workstation]
- OS Version: [35]
- FreeTube version: [16.0 Beta]

Fix thumbnail being obstructed by time tooltip

---

src/renderer/components/ft-video-player/ft-video-player.js

closes #2146
>On YT if the playback speed is 2x and fast forward one time, it will fast forward 10sec instead of 5sec.
It also skips less when rate < 1 (same as youtube)
Change playback rate and interval then press J, L Left arrow & Right arrow.
- OS Version: 21H1
- FreeTube version: 2bbb875749e52b6f8e70f20560edf9d584a0e2ff

Fast forward = Playback rate × Interval

---

src/renderer/App.js

---
Only fetch the most recent update from the GitHub releases
---
n/a
Instead of fetching a full page (default 30) releases from the GitHub API when checking for updates, only fetch the first item, this reduces the response from ~50kB to ~4.4kB. This should make checking for updates significantly faster.
n/a
Has this pull request been tested? **Yes**
Please describe shortly how you tested it and whether there are any ramifications remaining. **No additional errors were …

Only fetch the most recent update from the GitHub releases

---

package.json
yarn.lock

N/A
Update electron to [16.2.2](https://github.com/electron/electron/releases/tag/v16.2.2)
Several security fixes included
N/A
N/A
- OS: MacOS
- FreeTube version: 5c54862a765ca2d229bb7df72307bb56ebee18b1

Update electron to 16.2.2

---

src/renderer/components/ft-video-player/ft-video-player.js

---
Switch debug and picture in picture shortcuts for consistency
---
Partially addresses #2138 
Switches the PiP shortcut (d) with the debug shortcut (i) for consistency with Youtube's own shortcuts. See the related issue.
- OS: [e.g. iOS] Debian
- OS Version: [e.g. 22] 11
- FreeTube version: [e.g. 0.8] v0.16.0 Beta

Switch debug and picture in picture shortcuts for consistency

---

src/renderer/App.js
src/renderer/components/ft-input/ft-input.vue
src/renderer/components/top-nav/top-nav.js
src/renderer/components/top-nav/top-nav.vue

---
Fix search input shortcut
---
Partially addresses #2138
Closes #1463
Adds a keyboard shortcut for focusing the search bar.
- OS: [e.g. iOS] Debian
- OS Version: [e.g. 22] 11
- FreeTube version: [e.g. 0.8] v0.15.0 Beta
I think we should think about adding styling for the focused state of inputs, currently it's not obvious when an input is focused due to the lack of visual changes.

Fix search input shortcut

---

src/renderer/store/modules/utils.js
src/renderer/views/Trending/Trending.js

---
Fix: trending cache
---
None
Trending pages weren't getting cached properly so multiple requests could have been made that weren't wanted/needed when navigating through the trending pages
Switch the trending page tabs and see it load properly without logging (invidious and local api use console logging)
- OS: Windows
- FreeTube version: 0.16.0

Fix: trending cache

---

src/renderer/views/History/History.vue
src/renderer/views/UserPlaylists/UserPlaylists.vue

---
Hide filter on history and playlist page when page is empty
---
Closes #2174 
Hides the search bar on history and playlist pages when they pages are empty
_Playlists:_
_History:_
I tested this by adding and removing videos from the playlists and watching and removing items from the watch history.
- OS: Windows
- FreeTube version: 06a7298ded743c1db59f6b946ed038f996bd3340

Hide filter on history and playlist page when page is empty

---

src/renderer/App.js

---
Add the alternate search keyboard shortcuts COMMAND+L on MacOS and CTRL+L on other platforms
---
Implements the alternate shortcuts discussed here: https://github.com/FreeTubeApp/FreeTube/pull/2140#issuecomment-1092388334
This pull requests adds an alternative keyboard shortcut to focus the search bar, `COMMAND+L` on MacOS and `CTRL+L` on other platforms.
- OS: Windows/MacOS
- OS Version: 10/Monterey
- FreeTube version: 06a7298ded743c1db59f6b946ed038f996bd3340

Add the alternate search keyboard shortcuts COMMAND+L on MacOS and CTRL+L on other platforms

---

.github/workflows/autoLabelPR.yaml

---
Auto label the PR when submitted
---
Partially addresses https://github.com/FreeTubeApp/FreeTube/issues/1720
When PR is submitted the waiting for review label will be added. Also if a PR is reopened the label will be added.
1. go to https://github.com/efb4f5ff-1298-471a-8973-3d47447115dc/FreeTube/tree/autoLabelPR
2. submit a pr

Auto label the PR when submitted

---

src/renderer/views/Watch/Watch.js

---
Allow DASH formats for livestream replays
---
Currently FreeTube enforces the legacy formats for all livestreams regardless of whether they are live or replays. This pull requests allows DASH formats to be used for livestream replays.
Before:
After:
I tested various videos to check that nothing broke. Here is an example of a livestream replay video that has DASH formats after this change: https://youtu.be/TEygSwHWhfA
- OS: Windows
- FreeTube version: 7878e9e3a671830426bc0893a44c1baff5801cb9

Allow DASH formats for livestream replays

---

src/renderer/components/ft-list-video/ft-list-video.js

On the channel view (and pretty much anywhere with a `ft-list-video` component), after removing a seen video from history through the context menu, the page would still remember the watch progress and delegate it to the external player afterwards, which was very annoying since most of those videos' previous watch progress is basically at the end of the video.
This PR clears that view's cached watch progress value after removing the video from history.
**Additional notes**
I personally don't care, but I'll leave it here as a note in case someone wants to look into it.
I noticed that the watch progress bar value doesn't always seem to be accurate.
It's possible that the calculation for this value is badly done or the values provided to the calculation …

Clear watch progress from view cache when removing video form history

---

src/renderer/components/ft-video-player/ft-video-player.js
src/renderer/views/Watch/Watch.js

---
Hide Picture in Picture button and disable keyboard shortcut for audio formats
---
<details><summary>Before</summary>
</details>
<details><summary>After</summary>
</details>
**Testing**
I tested various videos and checked that it works regardless of which formats are set as default and that it works when the formats are changed on the video page. The video used for the screenshots is this one: [https://youtu.be/lIxAPW0YAEU](https://youtu.be/lIxAPW0YAEU)
- OS: Windows
- FreeTube version: e29d041a91fe78e96b62ac8cd61d8d8a78797ab7

Hide Picture in Picture button and disable keyboard shortcut for audio formats

---

package.json
yarn.lock

Update marked to [4.0.15](https://github.com/markedjs/marked/releases/tag/v4.0.15)
Changelog 4.0.15:
> Bug Fixes
>
> *    list item bullet without whitespace
Changelog [4.0.14](https://github.com/markedjs/marked/releases/tag/v4.0.14):
> Bug Fixes
> 
> *    only convert leading tabs to spaces
Update ytsr to [3.8.0](https://github.com/TimeForANinja/node-ytsr/releases/tag/v3.8.0)
Changelog 3.8.0:
> Features
> 
> *    add support for chipCloudRenderer
Changelog [3.7.0](https://github.com/TimeForANinja/node-ytsr/releases/tag/v3.7.0):
> Features
> 
> *    add support for reelShelfRenderer
**Testing**
* `ytsr`: I checked that searching still worked and no errors appeared
* `marked`: I changed the version in the package.json file to "0.15.0" to force the …

Update marked to 4.0.14 and ytsr to 3.8.0

---

.github/workflows/build.yml
.github/workflows/linter.yml
.github/workflows/release.yml

N/A
Update all GH Action config to use Node 16.x instead of 14.x
[16.x is the latest LTS version now](https://nodejs.org/en/blog/release/v16.13.0/)
N/A
No testing done...
Well I am using Node 16.x locally for running FT in dev
- OS: N/A
- OS Version: N/A
- FreeTube version: N/A

* Update all GH workflow config to update node 14.x > 16.x

---

src/renderer/views/Channel/Channel.js

Closes #2214
Banner: Invidious returns "authorBanners": [ ] for channels without banners, results in "TypeError: Cannot read properties of undefined (reading 'url')"
example: UC3VHfy8e1jbDnT5TG2pjP1w (Nyan cat)
Playlist:
> Subscribe to a few channels with playlists (to access them from sidebar)
> Reload (Ctrl R)
> View "Playlists" tab of one of the channels
> View another channel's playlists (without visiting other pages in between)
> It will display either "This channel does not currently have any playlists" or wrong playlists
Shows defaultBanner.png
Visit a channel without …

channel fix (banner, playlist)

---

src/renderer/components/ft-input/ft-input.js

---
Prevent search input reset from overwriting clipboard on Linux
---
Closes #2019
Removes the input event emitter in favour of a more standard way of clearing an input field to prevent clipboards being overwritten.
Test with any form of selection-based clipboards (middle mouse button on most Linux systems). Select any text, use middle mouse button to paste, type something else into FreeTube search, click the X button to clear it, paste again.
- OS: [e.g. iOS] Debian
- OS Version: [e.g. 22] 11
- FreeTube version: [e.g. 0.8] v0.16.0 Beta …

Prevent search input reset from overwriting clipboard on Linux

---

_scripts/build.js

Extracted from #1888 in case that PR is not updated
Build script run on MacOS would detect CPU type (name matching) and build binary with corresponding architecture
which is `x64`/`arm64`
Running process of locally built binary:
- `npm run build --if-present`
- Run built binary
- Check "Kind" in activity monitor
- OS: MacOS
- OS Version: 12.0.1
- FreeTube version: 341968c8223873db084b8ad80ed1e723d0feaa58
This does **not** include build action update
[GH runner does not support it …

Update build script to build ARM64 version on Apple Silicon machines

---

src/renderer/components/ft-video-player/ft-video-player.js

---
Title
---
By default the video.js modal component calls [`.stopPropagation()` on all `keydown` events](https://github.com/videojs/video.js/blob/main/src/js/modal-dialog.js#L450-L453), even though it only uses the tab and escape key events. To fix this issue this pull request replaces the handler and only calls the original one if the event is caused by the escape or tab keys, otherwise it ignores it which allows the event to progate unhindered to the event handler on the document.
I tested that the tab and escape key events are still passed on to the modal and that other keyboard shortcuts are captured by the event handler on the document and work correctly.
**Desktop …

Fix the stats for nerds modal hogging all the keyboard events

---

src/renderer/components/ft-video-player/ft-video-player.js
src/renderer/components/watch-video-playlist/watch-video-playlist.js

---
Add support for next/previous/pause/resume global hotkeys/actions
---
Related to https://github.com/FreeTubeApp/FreeTube/issues/2138
Closes #1931
This pull request adds support for the global next and previous track hotkeys/actions inside of playlists. As I'm using the MediaSession API this also works with the next and previous track actions on my Bluetooth headphones.
As there have been issues with the play/pause hotkeys on non Windows operating systems in the past, I've also added explicit handlers for those. I also made it explicitly report the playback state (playing, paused, none) to the MediaSession API. I can remove these handlers and explicit reporting of the playback state if we are sure that those issues have been fully …

Add support for next/previous/pause/resume global hotkeys/actions

---

src/renderer/components/data-settings/data-settings.js

---
Fix: csv import/export
---
closes #2219 
Removes blank lines from csv files when importing, adds quotation marks to channel names that have commas in them for exporting
I imported and exported the csv file provided in the issue and the import and export worked
- OS: Windows
- FreeTube version: 0.16.0

Fix: csv import/export

---

src/renderer/views/Channel/Channel.js

closes #1545
Holds id in `getChannelInfoInvidious` etc. and compares to this.id, if they are different (route changed), do nothing.
Before:
<video src="https://user-images.githubusercontent.com/80553357/169692829-4ff6cc7e-bb4a-4d21-9c9c-64141c790d00.mp4">
After:
<video src="https://user-images.githubusercontent.com/80553357/169692835-16c137be-daa9-4c17-b92f-bea410e2ae74.mp4">
- OS: Windows10
- OS Version: 21H1
- FreeTube version: 75d59a54990280c08488cb39ba136d2b38c9d0fe

Fix: wrong info displayed when quickly navigate from a channel to another

---

src/renderer/views/Watch/Watch.js

closes #2265
1. Set API to Local
2. Set Language to anything but English (US, UK or System)
3. Watch any video with caption and receive error.
Also remove duplicate translations in `tryAddingTranslatedLocaleCaption`
Before: API Error
After:
- OS: Windows 10 21H1
- FreeTube version: 2332aafd68834e421bec8c75977b3dd12691f62f

Fix caption baseurl

---

src/renderer/components/ft-sponsor-block-category/ft-sponsor-block-category.js
src/renderer/components/ft-sponsor-block-category/ft-sponsor-block-category.sass
src/renderer/components/ft-sponsor-block-category/ft-sponsor-block-category.vue
src/renderer/components/ft-video-player/ft-video-player.js
src/renderer/components/sponsor-block-settings/sponsor-block-settings.js
src/renderer/components/sponsor-block-settings/sponsor-block-settings.vue
src/renderer/components/theme-settings/theme-settings.js
src/renderer/store/modules/settings.js
src/renderer/store/modules/utils.js
static/locales/en-US.yaml

---
Sponsorblock improvements
---
closes #1840 (All categories implemented)
closes #1440 (User decides color for each category)
#1380 (Auto-skip is now optional, no prompt to skip however)
This PR allows users to configure each SponsorBlock category individually (Color + Skip Mode)
Skip Modes:
- Don't Skip (No indication of sponsor will be shown in seek bar)
- Show In Seek Bar (Show the sponsored segment in the seek bar but don't autoskip)
- AutoSkip (AutoSkip when the video reaches the sponsored segment)
Mode not included (Might do a future PR to implement it):
- Prompt To Skip (Have a "Skip Sponsored Segment" button appear when a sponsored segment is reached)
**Screenshots (if …

Feat: SponsorBlock improvements

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/feature_request.yaml

---
Update issue templates
---
I got the feeling that nobody is searching our [documentation](docs.freetubeapp.io) before opening up an issue. That leads us to spending our time responding to people with answers they could have found in the docs.
Not sure if I've worded it clear enough what people must do before opening up an issue

Update issue templates

---

_scripts/dev-runner.js
src/renderer/components/ft-icon-button/ft-icon-button.js
src/renderer/components/ft-icon-button/ft-icon-button.sass
src/renderer/components/ft-icon-button/ft-icon-button.vue
src/renderer/components/ft-list-video/ft-list-video.js
src/renderer/components/ft-list-video/ft-list-video.vue
src/renderer/components/watch-video-info/watch-video-info.js
src/renderer/components/watch-video-info/watch-video-info.vue

IRC chat:
```
Non-pressing question: if we were to ever have breakout sections on hover of the three dots video section dropdown, would the better organization be "Open >" & "Copy >" or "YouTube >" & "Invidious >"?
```
- Update the dropdown opened by a button with title "More Options",  
located on video card/box rendered in views like search result/history/trending,  
so that the options are reordered and group together.  
Dividers are used for grouping.  
- Menu item spacing reduced slightly.
New screenshots (all dropdown updated by this PR, too lazy to take for all themes)
Old screenshots (before divider opacity reduced):
**Testing (for code that is …

* Implement divider for video "more dropdown menu"

---

src/main/index.js
src/renderer/App.js

#1809
2be2301d92e37d13a4839ded1fc436836292b7d4 only fixes the issue partially so that any click results in opening in **current** window
But the expected behaviour is to open links clicked by middle mouse button in **new** window
https://user-images.githubusercontent.com/1018543/154211025-302ab845-91ef-4a00-8bf0-f06a4b39f255.mov
- Use app to view https://youtu.be/qNWNArktMvY
- Open comment to find comment with video URL (which should be https://www.youtube.com/watch?v=uh24rV65Amg&list=PLzFTGYa_evXjqH9QWC2xwdfS87fYxtBcv&index=5&t=0s)
- Click on the link (try with both left & …

Fix handling of youtube link middle mouse click

---

package.json
src/renderer/store/modules/sponsorblock.js
yarn.lock

---
Use the subtle crypto library built-in to Electron instead of node-forge
---
Currently FreeTube uses the [node-forge](https://www.npmjs.com/package/node-forge) library to generate the hash prefix of the video id that it sends to the SponsorBlock API. This pull request removes the need for that dependency by using the [digest](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/digest) function provided by the SubtleCrypto library which is built into all modern webrowsers (added to Chrome in v37, FreeTube uses Electron 16 -> Chrome 96).
I tested various different videos and it worked the same as it did before this pull request.
Example videos: …

Use the built-in subtle crypto library instead of node-forge

---

package.json
src/renderer/store/modules/ytdl.js
src/renderer/views/Playlist/Playlist.js
yarn.lock

---
Format playlist dates with the selected locale
---
Currently FreeTube uses the dateFormat function provided by the [dateformat](https://github.com/felixge/node-dateformat) dependency to format the date for playlists when the Invidious API is selected as a backend. It does a good job of formatting the date however it doesn't respect the users selected locale, to fix this we can use the `Date.prototype.toLocaleDateString()` function that is built into JavaScript. The only downside is that we loose the ordinals (e.g. `9th` -> `9`).
This also fixes the date having 1 day added on to it (not sure why that was there in the first place).
I used German for the screenshots as the difference is clearly visible on the …

Format playlist dates with the selected locale

---

src/renderer/components/ft-profile-selector/ft-profile-selector.css
src/renderer/components/top-nav/top-nav.sass

---
Even spacing on top-nav
---
Tiny adjustments to the top-nav
* Even spacing for all action buttons on left side
* Hover indicator for profile button
* Profile button is matched in width/height to the rest of the buttons for visual consistency
The changes are pretty subtle, they don't really show well on screenshots.
Simulated smaller screens and just had a general look around profile sections to see if anything is amiss!
- OS: [e.g. iOS] 10
- OS Version: [e.g. 22] Debian

Even spacing on top-nav

---

src/renderer/components/ft-input/ft-input.css
src/renderer/components/ft-input/ft-input.js
src/renderer/components/ft-input/ft-input.vue

---
Clean up ft-input for top-nav
---
N/A
Fragmentation of #1793, slightly cleans up ft-input logic.
* Removed setTimeout for transition and opted for a CSS solution instead
* Made both clearInputTextButton and actionButton the same width/height for visual consistency
Before:
After:
Looked through the app and tried to input text anywhere I could to check for visual errors.
- OS: [e.g. iOS] Debian
- OS Version: [e.g. 22] 10
Feels like we need an …

Clean up ft-input for top-nav

---

src/renderer/store/modules/settings.js

---
Improve system locale selection
---
None
For locale set to system, If a user's system locale is not found then it will default to a locale with the same language instead of defaulting to 'en-US'
Yes this PR has been tested by hardcoding the value here to a different locale:
https://github.com/FreeTubeApp/FreeTube/pull/2271/files#diff-ef55248451a73d0a2680edeb9d5bbd8a6d0a3deaa89406c100d29fef7a45e497R236 
- OS: Windows
- FreeTube version: 0.16.0

Improve system locale selection

---

src/renderer/App.css
src/renderer/App.vue
src/renderer/components/side-nav/side-nav.css
src/renderer/components/top-nav/top-nav.js
src/renderer/components/top-nav/top-nav.sass
src/renderer/components/top-nav/top-nav.vue
src/renderer/themes.css
src/renderer/views/Watch/Watch.sass

---
Remove usage of fixed positioning for core UI elements
---
N/A
This PR attempts to remove the usage of margins for positioning the UI elements (routerView, top-nav, side-nav, etc.) and replace it with a more modern approach using flexbox and sticky positioning.
* Remove position: fixed from top-nav and side-nav
* Reduce z-index position of side-nav to make it not overlap the box-shadow on the top-nav
* Make video infoArea sticky so it follows users scroll (in the case there are many suggested videos)
Before:
After:
Before:
After:
I ran through most of the app, making sure …

Remove usage of fixed positioning for core UI elements

---

src/renderer/store/modules/subscriptions.js
src/renderer/views/Channel/Channel.js
src/renderer/views/Channel/Channel.vue
src/renderer/views/Subscriptions/Subscriptions.css
src/renderer/views/Subscriptions/Subscriptions.js
src/renderer/views/Subscriptions/Subscriptions.vue
static/locales/en-US.yaml

---
Allow Unsubscribing from Deleted Channels
---
closes #2133 
closes #1231 
closes #1590
closes #555
This PR will try to find channels that may have been deleted when your subscriptions get loaded (except when using Invidious that's not in RSS) and it allows you to load the subscription information that is saved when viewing a channel page
Has this pull request been testedZ
I was able to get the links of two channels that were deleted for different reasons and I tested:
**refreshing the Subscription page** with 
- Local API + RSS
- Local API + RSS Disabled
- Invidious + RSS
- …

Allow Unsubscribing from Deleted Channels

---

src/renderer/components/ft-input/ft-input.css

---
Fix ft-input bug padding
---
#2279
Fixes bug found by @PikachuEXE https://github.com/FreeTubeApp/FreeTube/pull/2279#issuecomment-1144835903
I made the padding trick only happen on the main search input, this should fix it for the rest of the inputs across the app.
- OS: [e.g. iOS] 10
- OS Version: [e.g. 22] Debian
Thanks for catching it pika

Fix ft-input bug padding

---

src/main/index.js

---
Fix the YouTube GDPR cookie not being sent along with requests
---
Fixes the empty GDPR consent cookie not being sent along with requests to YouTube. This fixes the trending tab and the channel community page (#1568) in Europe.
Yes, this change successfully fixed trending and the channel community page in Europe.
- OS: Windows
- FreeTube version:  v0.17.0-RC

Fix the YouTube GDPR cookie not being sent along with requests

---

src/renderer/store/modules/utils.js

None
I forgot to add '?'  and '*' to #2221 for win32
- OS: Windows 10 21H1
- FreeTube version: 0.16

Fix: screenshot forbidden chars on Windows

---

src/renderer/components/ft-video-player/ft-video-player.js

Closes #2312
>1. Clear Local Storage (Developer tools -> Application)
>2. Play a video
>3. Click "Toggle loop" button
>4. Doesn't work
- OS: Windows10 21H1
- FreeTube version: ae654a1581a47b6056fd321dc7b3fa865d3624b0

Fix: loop button

---

.github/workflows/linter.yml

---
Allow the lint workflow to run on all RC branches
---
Allows the lint workflow to run on all RC branches, as it is required for PRs to be merged.

Allow the lint workflow to run on the v0.17.0-RC branch

---

src/renderer/App.css
src/renderer/components/watch-video-description/watch-video-description.css
src/renderer/videoJS.css
src/renderer/views/Channel/Channel.css

---
Fix emojis displaying incorrectly (development branch)
---
Emojis are displayed incorrectly (colourless) on Windows, this pull request fixes it by adding the emoji fonts to any place in FreeTube that might contain emojis. The list of emoji fonts was taken from Bootstrap's stylesheet [twbs/bootstrap - scss/_variables.scss#L543](https://github.com/twbs/bootstrap/blob/main/scss/_variables.scss#L543).
<details><summary>Before</summary>
Search:
Channel:
Subscriptions:
Watch page:
Fullscreen player:
</details>
<details><summary>After</summary>
Search:
Channel:
Subscriptions:
Watch page:
Fullscreen player:
</details>
I tested this by checking all …

Fix emojis displaying incorrectly

---

src/renderer/components/ft-share-button/ft-share-button.sass

---
Fix the theming of the share menu logos for the system, black and dracula themes (development branch)
---
This pull request fixes the YouTube and Invidious logos being invisible in the share menu when the system, black or dracula themes are active.
<details><summary>System</summary>
</details>
<details><summary>Black</summary>
</details>
<details><summary>Dracula</summary>
</details>
I tested this pull request by changing the theme and checking that the logos are visible regardless of the selected theme.
- OS: Windows …

Fix the theming of the share menu logos for the system, black and dracula themes

---

package.json
yarn.lock

---
^ Update marked
---
Update the [`marked`](https://github.com/markedjs/marked/releases) dependency to the latest version.
Changelog:
- 4.0.17:
- Bug fix: Code and heading after list without blank line
- 4.0.16:
- Bug fix: fix ref links inside table
I tested that the changelog markdown is still being parsed correctly by changing the version in the package.json file to a lower version.
- OS: Windows
- FreeTube version: 330086e87c1f2eb074d8e92d8d3d5f7f6b372358

^ Update marked

---

src/main/index.js

---
Fix confusing zoomin shortcut
---
Closes #1247 
Adds a "hidden" global shortcut for zooming in (ctrl + equals) that should fix some of the confusion over the zoomin shortcuts, also adds zoom shortcuts using numpad (numpad +, -, and 0) to mirror browser behaviour.
Zoom in and out a bunch with keyboard shortcuts :)
- OS: [e.g. iOS] 10
- OS Version: [e.g. 22] Debian
I tried to do some digging into how we could sync UI scale with the zoom properly, sadly I didn't come to any clear …

Fix confusing zoomin shortcut

---

src/renderer/store/modules/utils.js

None
[addressed here](https://github.com/FreeTubeApp/FreeTube/discussions/2309#discussioncomment-2934372)
1. Replace forbidden chars
2. EISDIR when `downloadFolderPath` is not empty
1. Tested with these videos. could not find < and >
- [xcRxwi0x5ig](https://youtu.be/xcRxwi0x5ig) Prehistoric Planet — Uncovered: Did Velociraptor Have Feathers? | Apple TV+
- [e5NLW_c8i7g](https://youtu.be/e5NLW_c8i7g) \*MUSIKVIDEOS Som BEVIS\* RAPPARE & GÄNGMEDLEMMAR DÖMDA TILL FÄNGELSE
- [pwAMJG1BMB0](https://youtu.be/pwAMJG1BMB0) Blaze & Monster Machines "Let's Blaze!" Compilation!
- [Kx_eAKYnn-g](https://youtu.be/Kx_eAKYnn-g) How to find …

Fix download filename problems

---

src/renderer/components/ft-channel-bubble/ft-channel-bubble.css

---
Fix channel names being cut off
---
Closes #2291 
Adds ellipsis overflow to featured channel names
**Testing**
1. Go to channel: https://www.youtube.com/c/Whitelight
2. Go to "About" tab
3. Compare Feature Channel "MandaloreGaming" between upstream and PR.
Before:
After:
- OS: [e.g. iOS] 10
- OS Version: [e.g. 22] Debian

Fix channel names being cut off

---

src/main/index.js
static/locales/en-US.yaml

#1869 Partially
Update app menu to add item for new window
with keyboard shortcut
https://user-images.githubusercontent.com/1018543/173169981-cdab77a2-b298-4d56-ae33-25da4f46b006.mov
- Use new menu item to create new window
- Use new keyboard shortcut (Ctrl/Cmd + N) to create new window
- OS: MacOS
- OS Version: 12.4
- FreeTube version: e861e70b3374b10430a3f657b626c7f14fc22bea

* Update app menu to add item for new window

---

src/renderer/views/Watch/Watch.js

---
Fix removing the meta files when navigating to a new video (RC branch)
---
closes #1562
If you are watching a video and go to the next video the videoId property on the component (`this.videoId`) changes before the ipc call for the userdata directory returns, so previously that would mean that the old dash and storyboard files wouldn't get deleted and potentially also deleting the ones for the new video, if they are already created at that point. This pull request changes it so that the videoId value is passed in as a function parameter, this means that it isn't affected by `this.videoId` changing while the function is running asyncronously.
This pull request also removes the redundant existence checks for the directories as the …

Fix removing the meta files when navigating to a new video

---

.github/ISSUE_TEMPLATE/bug_report.yaml

---
Make installation method and API method mandatory in bug issue template
---
In the past people neglected to mention in an API related issue, what API they were using or installation method they were using in a installation they used that broke FT.
This was because the fields were not mandatory.
I need some help on deciding what to do with the position of the API field. I would like to see all the mandatory fields first but i dont know what position sounds logical to move the API field to. Also im feeling a bit conflicted about changing the position because of the already logical order of all the fields.

Make installation method and API method mandatory in bug issue template

---

src/renderer/components/ft-input/ft-input.js
src/renderer/views/History/History.vue
src/renderer/views/UserPlaylists/UserPlaylists.vue

#2346
>1. Add items to userplaylists and history
>2. Filter to show fewer results
>3. Click "Clear input"
>4. Filter state persists, not showing all items
Before
<video src="https://user-images.githubusercontent.com/80553357/174777700-f4107b9b-5a10-4425-bfae-4894a27a4ac7.mp4">
After
<video src="https://user-images.githubusercontent.com/80553357/174777514-28d4f9ef-6caf-460c-951e-6f6efd26cec8.mp4">
- OS: Windows10 21H1
- FreeTube version: d1a7bc301103f3680ae06882449703d7828c0fed

Clear filter when clicked "Clear input" [0.17RC]

---

src/renderer/components/ft-input/ft-input.js
src/renderer/views/History/History.vue
src/renderer/views/UserPlaylists/UserPlaylists.vue

#2346
>1. Add items to userplaylists and history
>2. Filter to show fewer results
>3. Click "Clear input"
>4. Filter state persists, not showing all items
Before
<video src="https://user-images.githubusercontent.com/80553357/174777700-f4107b9b-5a10-4425-bfae-4894a27a4ac7.mp4">
After
<video src="https://user-images.githubusercontent.com/80553357/174777514-28d4f9ef-6caf-460c-951e-6f6efd26cec8.mp4">
- OS: Windows10 21H1
- FreeTube version: d1a7bc301103f3680ae06882449703d7828c0fed

Clear filter when clicked "Clear input"

---

src/renderer/App.js

---
Fix right clicking on links being treated as link clicks (development branch)
---
closes #2343
This PR fixes right clicking on links opening them instead of the context menu showing up.
Right click on a bunch of links, with this PR only the context menu should show up.
- OS: Windows
- FreeTube version: 4f4f727ae1af304ce3131f03b29383ce4fdbb724

Fix right clicking on links being treated as link clicks

---

src/renderer/i18n/index.js

---
[dev] Allow more locales to be used by FreeTube
---
I noticed a lot of changes recently for languages that are not currently displayed in the FreeTube app
This PR allows the following locales to be selected:
ca (català/catalan), es_AR, et (Eesti/Estonian), eu (euskera/basque), ko (한국인/ korean), lt (lietuvių/lithuanian)
I tested by changing my locale to the languages that were added.
- OS: Windows
- FreeTube …

[dev] Allow more locales to be used by FreeTube

---

src/renderer/components/watch-video-description/watch-video-description.css

---
Fix long video links in the video description breaking the layout (dev branch)
---
closes #2380
This pull request fixes long links in the video description breaking the layout of the watch page because they weren't getting wrapped correctly.
Before:
After:
I tested it with the URL provided in the issue https://youtu.be/7pfxHoAnCkE.
- OS: Windows
- FreeTube version: c501e0d301050da3e6205741f6cffb9a728845bb

Fix long links in the video description breaking the layout

---

src/renderer/components/ft-input/ft-input.js
src/renderer/components/ft-input/ft-input.vue

---
Fixes search suggestion issues with arrow keys (development branch)
---
closes #1741
This pull request fixes the cursor moving in the search bar when the up and down arrow keys are used to navigate through the search suggestions.
It also fixes the search suggestions being updated for all keyboard events even when the value of the search bar doesn't change (e.g. left and right arrow keys). Currently the search suggestions get updated for the `input` and `keydown` events, the `input` only gets fired if the value of the field changes, `keydown` is fired for all keyboard events.
It also replaces uses of the deprecated `event.keyCode` property with `event.key`, this improves code readability as you don't need to go and look up which …

Fixes search suggestion issues with arrow keys

---

src/renderer/components/ft-tooltip/ft-tooltip.js

---
Replace sketchy lodash import for tooltip ids with own implementation
---
Currently `lodash` is being imported and included in FreeTube despite FreeTube not declaring it as a dependency.
Why did it still work?
Some of FreeTube's development dependencies depend on lodash, so lodash is in the node_modules folder. Webpack doesn't care if you've declared it as a dependency in the `package.json` file, as long as it can find it it will successfully import it. As we haven't declared it as a dependency, the build script wasn't picking lodash up as an external dependency, so webpack just inlined lodash into the renderer.js file. Due to us using commonjs imports webpack wasn't able to treeshake lodash so it included all of lodash, not just the `uniqueId` …

Replace sketchy lodash import for tooltip ids with own implementation

---

_scripts/build.js
_scripts/webpack.main.config.js
_scripts/webpack.renderer.config.js
_scripts/webpack.web.config.js
_scripts/webpack.workers.config.js
package.json

---
Prevent packaging unneeded dependency files
---
FreeTube's dependencies ship a lot of files that might be useful during development, these files aren't useful for users of FreeTube. As we don't have any control over the majority of the dependencies, we can exclude the files during the electron build and reduce the package size (`resources/app.asar`: 54.2MB -> ~49.5MB~ 35.2MB). This pull request also fixes the webpack builds no longer properly ignoring dotfiles.
I tested this by running `yarn run build` and then checking the files produced by the webpack builds in the `dist/` directory and the files produced by the electron build in the `build/` directory. I also clicked …

Prevent packaging unneeded dependency files

---

src/renderer/App.css

Fix style issue introduced in #2398
`margin-top` with 60px seems way too much even for narrow windows not to mention wide windows
There are 2 window size variants tested (according to affected stylesheet's media queires)
<details>
<summary>> 680px</summary>
</details>
<details>
<summary><= 680px</summary>
</details>
- OS: MacOS …

Fix style issue introduced in #2398

---

src/renderer/components/subscription-settings/subscription-settings.js
src/renderer/components/subscription-settings/subscription-settings.vue

---
Title
---
Fixes the blank space in the subscription settings.
before:
after:
- OS: Windows
- FreeTube version: 3ccdf566998fc88350d55797c936b6014d65551c

Fix blank space in the subscription settings

---

src/renderer/App.css

Fix style issue introduced in #2399
`margin-top` with 60px seems way too much even for narrow windows not to mention wide windows
Please refer to #2405 
Tested locally (same as #2405)
- OS: MacOS
- FreeTube version: 9a01030919003e4dfb5826240de21d564aaea805

! Fix style issue introduced in https://github.com/FreeTubeApp/FreeTube/pull/2399

---

src/renderer/components/watch-video-info/watch-video-info.js
src/renderer/components/watch-video-info/watch-video-info.vue
src/renderer/views/Watch/Watch.js
src/renderer/views/Watch/Watch.sass
src/renderer/views/Watch/Watch.vue

---
Fix scrolling through the download dropdown (development branch)
---
works around issues introduced in #2284
This pull request fixes the issue with not being able to scroll through the download dropdown. It toggles the sticky css position on the video info section when the downloads menu is open. It also includes some extra code to make the toggling feel seemless.
I tested this PR both on wide and narrow screens and was able to scroll though the download dropdown without an issues.
- OS: Windows
- FreeTube version: 0.17.0 RC/development (9fa4a5a36eb46cb7c2fb6d3d6a17749df5efbc97)

Fix scrolling through the download dropdown

---

src/renderer/App.css
src/renderer/App.vue

---
Fix banner width (RC branch)
---
Makes the banners the same width as the cards below them.
I tested both the new blog and update banners.
- OS: Windows
- FreeTube version: 0.17.0 RC

Fix banner width

---

src/renderer/views/Watch/Watch.js

---
Respect autoplay playlists setting
---
Closes #2362
Fixes the issue where the "Autoplay Playlists" setting wasn't being respected by the app.
Attempted watching a playlist with the setting disabled and letting a video end. Attempted watching a playlist with the setting enabled and letting a video end. Both scenarios act as expected.
- OS: Fedora
- OS Version: 35
- FreeTube version: Version v0.17.0 RC

Respect autoplay playlists setting

---

src/renderer/components/proxy-settings/proxy-settings.js
src/renderer/components/proxy-settings/proxy-settings.vue

---
Fix Proxy Test URL
---
Closes #2389
Our previous site for testing the built in proxy stopped working. The URL has been updated to use https://ipwho.is/ instead of the existing one.
Enable Tor Proxy. Click on the "Test Proxy" button. Results are shown as expected.
- OS: Fedora
- OS Version: 35
- FreeTube version: v0.17.0 RC

Fix Proxy Test URL

---

src/renderer/components/general-settings/general-settings.js

---
Drastically improve loading speed of the settings page
---
This pull request fixes the slow loading of the settings page by only loading the language list once, instead of the 45 times it does it at the moment (once outside of the loop and once for each language inside the loop). As the list of language names is also regenerated when you choose a different language, this change also speeds up that as well.
<details><summary>Illustration of what it feels like to open the settings page now:</summary>
</details>
Here is how long it takes to generate the list of language names with and without this change. The numbers are in milliseconds.
**Testing (for code that is not …

Drastically improve loading speed of the settings page

---

src/renderer/components/watch-video-comments/watch-video-comments.vue

- Bugfix
None
YouTube's reply count is unreliable. If I had to wager a guess, it's probably because comments that have been flagged/removed by the system don't decrement the counter at all.
This PR changes the visibility condition of the "Show More Replies" to check if the continuation token is null or not, which is, as far as I can see, reliable without a fault.
**Testing / Screenshots**
Tested video: https://www.youtube.com/watch?v=cMIgU6YlsEw (pinned comment)

Watch: Fix "Show More Replies" button visibility condition

---

src/renderer/components/top-nav/top-nav.js
src/renderer/store/modules/utils.js
src/renderer/views/Channel/Channel.js

---
Fix channel page ID handling
---
closes #2420
fixes a race condition introduced by #2259
This pull request resolves two issues relating to the handling of channel IDs on the channel page.
1. Treat `/channel/`, `/user/` and `/c/` channel URLs differently, as a `/user/` and `/c/` URLs with the same id might point to different channels.
2. Fixes the race condition introduced by #2259, that happens if fetching the info is faster than the video or playlist fetching. The issue is that after the info is fetched it overwrites the `id` property with the actual channel ID, so if you entered this URL `https://www.youtube.com/c/linustechtips`, the `id` property is set to `linustechtips` and when the info request returns it overwrites it with …

Fix channel page ID handling

---

src/renderer/components/external-player-settings/external-player-settings.js
src/renderer/store/modules/utils.js
static/external-player-map.json
static/locales/en-US.yaml
static/locales/es.yaml

---
External player choice 'None' translatable in Settings
---
closes #1670
Enables the translation of the word 'None' in the external player selector in the Settings menu. In order to do that the name of the first player is changed from 'None' to a translatable string and the whole array of names is translated. (Only the 'none' one has a translation, the other ones remain the same)
Just tested if the word is substituted by the one on the locales file …

External player choice 'None' translated in Settings

---

package.json
yarn.lock

---
Temporarily switch over to my fork of ytdl-core
---
closes #2467
closes #2468
YouTube made a change a couple of hours ago that broke ytdl-core's info extraction. This PR changes the ytdl-core dependency to use the branch on my fork that has the fix, while we wait for upstream ytdl-core to be updated.
The fix was found by @WaqasIbrahim in https://github.com/fent/node-ytdl-core/issues/1108#issuecomment-1212500413.
Yes. `yarn install` and then open any video with the Local API selected.
- OS: Windows
- FreeTube version: 0.17.0
This doesn't address any other …

Temporarily switch over to my fork of ytdl-core

---

.github/workflows/build.yml
.github/workflows/linter.yml

N/A
Update a few remaining `runs-on` from "ubuntu with specific version" (e.g. `ubuntu-20.04`, `ubuntu-18.04`)
to `ubuntu-latest`
Especially with ubuntu-18.04 deprecated
https://github.blog/changelog/2022-08-09-github-actions-ubuntu-22-04-is-now-generally-available-on-github-hosted-runners/
N/A
Just let workflow run
- OS: MacOS
- FreeTube version: a910e5f8041c0fa5c32243b8428bb4daf3b92617

Update all GH workflow to used `ubuntu-latest`

---

_scripts/build.js

---
Stop electron-builder trying to create GitHub releases in CI workflow
---
By default electron-builder will try to publish the built artifacts to GitHub releases, as we don't publish CI builds to GitHub releases and we handle the publishing ourselves, we don't need electron-builder to do that for us. Personally I think this should be an opt-in setting instead of an opt-out one but I guess the electron-builder developers see it differently.
The error message in the GitHub actions log:
```
InvalidConfigurationError: GitHub Personal Access Token is not set, neither programmatically, nor using env "GH_TOKEN"
at new GitHubPublisher (/home/runner/work/FreeTube/FreeTube/node_modules/electron-publish/src/gitHubPublisher.ts:4 …
```

Stop electron-builder trying to create GitHub releases in CI workflow

---

lefthook.yml
package.json
yarn.lock

Smaller version of #1171
For new comers not coming from #1171 
Git Hooks is `Git has a way to fire off custom scripts when certain important actions occur.` (quote from official doc)
There are client-side and server-side hooks but this PR is only about the client-side hooks.
For all available hook events and other stuff about Git Hooks see:
https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks
**Summary of changes**
- Add git hook via `lefthook`
- Git Hook scripts are generated by `lefthook` when installed via `yarn`, no extra step required
- Add a `pre-commit` hook to run `eslint` on every commit which lints staged (about to be committed) files only (faster) where the filenames end …

Add Git Hooks to run lint

---

src/renderer/views/Channel/Channel.js

---
Mapping the Invidious API field "authorId" to the expected field "channelId"
---
closes FreeTubeApp#2481
Added a line to map the field "authorId" to "channelId"
on the featured channels that come from the Invidious API
because the Channel view expects related channels to have
the property "channelId". 
```vue
<ft-channel-bubble
v-for="(channel, index) in relatedChannels"
:key="index"
:channel-name="channel.author || channel.channelName"
:channel-id="channel.channelId"
:channel-thumbnail="channel.authorThumbnails[channel.authorThumbnails.length - 1].url"
@click="goToChannel(channel.channelId)"
/>
```
- OS: Windows 10 
- OS …

Mapping the Invidious API field to the view

---

src/renderer/views/Channel/Channel.js

---
Fix unsubscribe from "All Channels" profile
---
None.
When on the "All Channels" profile, it should unsubscribe all channels from that channel. (It does this if you unsubscribe while on a channel's video but not from their Channel page)
Subscribe to a channel on a few profiles, unsubscribe to the channel from the "Channel" page on the "All Channels" profile
- OS: Windows …

fix unsubscribe from "All Channels" profile

---

src/renderer/components/ft-video-player/ft-video-player.js

#2485
Fix `Cmd+M` to be able to minimize a window when viewing a video
Tested on MacOS only
- View random video
- Test both `M` & `Ctrl/Cmd+M`
- OS: MacOS
- FreeTube version: 33cf88ce31c02b485951b6fdcdaf33969db78cdc
Documented keyboard shortcuts: https://docs.freetubeapp.io/usage/keyboard-shortcuts/

Fix Cmd+M unable to minimize window when viewing video

---

src/renderer/views/Playlist/Playlist.css

---
Fix playlist page sizing and layout
---
closes #2444
This PR fixes 3 styling issues with the playlist page:
1. The playlist page was styled with the `grid` display, making it space the videos out to fill the space if the playlist had less videos than space on the page. Changing this to `display: flex` and `flex-direction: column` fixes that behaviour.
2. The height of the info box currently overflows past the bottom of the window, I fixed this by changing the height calculation so that it has equally sized gaps at the top and the bottom of the info box.
3. The last issue was that the info box would scroll slightly when scrolling in playlists even though it's meant to stay in it's place. I fixed this by increasing the `top` …

Fix playlist page sizing and layout

---

src/renderer/components/watch-video-comments/watch-video-comments.js

---
Add support for bold, italics and strikethrough formatting in comments
---
closes #2404
yt-comment-scraper PR: https://github.com/FreeTubeApp/yt-comment-scraper/pull/41
_The majority of the changes are in yt-comment-scraper, this PR purely adds support for the yt-comment-scraper changes._
This pull request adds support for bold, italics and strikethrough formatting in comments.
before:
after:
1. Install the yt-comment-scraper PR: `yarn add "@freetube/yt-comment-scraper@git+https://github.com/absidue/yt-comment-scraper#parse-formatting"`
2. The comments under this video are a good place to test this PR (taken from this …

Add support for bold, italics and strikethrough formatting in comments

---

src/renderer/components/ft-video-player/ft-video-player.js
src/renderer/views/Watch/Watch.vue

---
Eliminating a race condition with SponsorBlock markers
---
closes FreeTubeApp#2492
This modifies the SponsorBlock markers to use the `lengthSeconds` already provided by the API to calculate their size and position instead of using `this.player.duration()`. `this.player.duration()` is 0 when the view loads and only obtains a value some time after. `lengthSeconds` should never be 0 unless the API is giving a strange response. Because of this, changing `this.player.duration()` to `lengthSeconds` should eliminate the race condition where `this.player.duration()` is 0 at the time when `addSponsorBlockMarker` is called.
(These are with Invidious API selected as primary) …

Eliminating a race condition with SponsorBlock markers

---

src/renderer/components/ft-video-player/ft-video-player.js

---
Removing an empty toast which was unintentionally introduced by my last pull request
---
related to FreeTubeApp#2493
This removes a toast which does not actually display any information and which was introduced by my last pull request.

Removing an empty toast

---

.babelrc
package.json
yarn.lock

Might or might not fix issue in #2113
Closes #2358
Closes #2406
Closes https://github.com/FreeTubeApp/FreeTube/pull/2359
16.x is not supported anymore
From https://www.electronjs.org/blog/electron-17-0
[Breaking change in 17.x](https://www.electronjs.org/blog/electron-17-0#breaking-changes) = 
- [`desktopCapturer.getSources`](https://www.electronjs.org/blog/electron-17-0#desktopcapturergetsources-in-the-renderer)
- The end
[Breaking change in 18.x](https://www.electronjs.org/blog/electron-18-0#breaking-changes) = 
- [Removed `nativeWindowOpen`](https://www.electronjs.org/blog/electron-18-0#removed-nativewindowopen)
- The end
[Breaking change in …

Upgrade electron from 16 > 20

---

package.json
yarn.lock

---
Switch back to upstream ytdl-core now that it has been updated
---
Upstream ytdl-core, has received an update (4.11.1) that resolves the issues properly, which means we can stop using my fork that had the quick fix in it. The changelog for the 4.11.1 is missing the most important part, that it includes this PR https://github.com/fent/node-ytdl-core/pull/1126 that updates the parsing logic.
Seems to work just as well, maybe even better than the quick fix on my fork.
- OS: Windows
I'll delete the branch on my fork when this is merged.

Switch back to upstream ytdl-core now that it has been updated

---

src/renderer/components/ft-input/ft-input.js
src/renderer/components/top-nav/top-nav.js

N/A
Opening a new window, loading channel and start searching seems wasting time
Browsers have search bar to open search in new tab/window already
Top nav search bar updated to open new window on shift click (on search/go button) or shift enter (on input bar)
Clicking search suggestion with shift still won't open a new window (Can be changed if needed)
https://user-images.githubusercontent.com/1018543/182007959-447e2b09-d365-4c73-803d-a17b1b7c3f34.mov
Enter 
- Random search string
- Channel/playlist/video URL
And perform
- Shift click on search/go button
- Shift + Enter …

Update top nav search input to open new window on shift click/enter

---

package.json
src/renderer/views/Search/Search.js
src/renderer/views/Trending/Trending.js
yarn.lock

---
Update yt-trending-scraper to 3.1.0
---
This pull request updates the yt-trending-scraper dependency to the latest release, 3.1.0.
I tested both the trending tab and the search results pages.
- OS: Windows

Update yt-trending-scraper to 3.1.0

---

package.json
yarn.lock

N/A
Update to electron 20.1.1 with [bug fix to `setBounds` used in FT](https://github.com/electron/electron/pull/35494)
Not sure how to test `setBounds`...
- OS: MacOS
- OS Version: 12.5.1
- FreeTube version: c0285c38c4db96bf548170fe0bf80fc827f865a5

^ Update electron 20.x

---

package.json
yarn.lock

---
Update yt-comment-scraper to 6.2.0
---
This pull request updates the yt-comment-scraper dependency to the latest release, 6.2.0.
I tested the comments under a few videos and didn't notice any new issues (for some reason YouTube 403's for some profile pictures).
I also checked that bold, italics and strikethrough showed up in comments under this video: https://www.youtube.com/watch?v=OqiXFXlYFi8 (same one as in #2475)
- OS: Windows

Update yt-comment-scraper to 6.2.0

---

_scripts/webpack.main.config.js
_scripts/webpack.renderer.config.js
_scripts/webpack.web.config.js
_scripts/webpack.workers.config.js

---
Only generate the web assets directory during web builds
---
This pull request stops the web assets directory being created during webpack builds that are only used for Electron packages. This doesn't make a big difference to the build duration, but it does stop webpack doing unnecessary work. While I was at it I also removed the references to the `LoaderOptionsPlugin` as that doesn't do anything in webpack 5, webpack 5 optimises during productions builds by default.
I decided to keep the asset copying in the main webpack config instead of moving it to the renderer one, as the renderer build is already a lot slower than the main one, so we might as well have the main build do it so that the renderer one doesn't take even longer (yes, I know that …

Only generate the web assets directory during web builds

---

package.json
yarn.lock

---
Update ytdl-core to 4.11.2
---
This pull request updates ytdl-core to the latest version, which supposedly fixes the regex issue we had for a few hours a couple of days ago, it doesn't seem to have broken anything so that's good.
I tested both `yarn dev` and `yarn build` and video playback still worked.
- OS: Windows

Update ytdl-core to 4.11.2

---

package.json
yarn.lock

---
Update copy-webpack-plugin dependency to 11.0.0
---
This pull request updates the `copy-webpack-plugin` dependency, the only breaking change is that the minimum node version for this plugin (at build time) is 14.15.0. Hopefully everyone is already using a much newer version than that anyway.
Full changelog here: https://github.com/webpack-contrib/copy-webpack-plugin/releases
Yes I tested `yarn dev` and `yarn build` and FreeTube worked in both cases.
- OS: Widows

Update copy-webpack-plugin dependency to 11.0.0

---

_scripts/build.js
_scripts/webpack.main.config.js
_scripts/webpack.renderer.config.js
src/renderer/components/ft-channel-bubble/ft-channel-bubble.vue
src/renderer/components/ft-icon-button/ft-icon-button.js
src/renderer/components/ft-input/ft-input.js
src/renderer/components/ft-input/ft-input.vue
src/renderer/components/ft-list-dropdown/ft-list-dropdown.vue
src/renderer/components/ft-list-playlist/ft-list-playlist.vue
src/renderer/components/ft-list-video/ft-list-video.vue
src/renderer/components/ft-notification-banner/ft-notification-banner.vue
src/renderer/components/ft-profile-selector/ft-profile-selector.vue
src/renderer/components/ft-select/ft-select.vue
src/renderer/components/ft-share-button/ft-share-button.vue
src/renderer/components/ft-tooltip/ft-tooltip.vue
src/renderer/components/side-nav-more-options/side-nav-more-options.vue
src/renderer/components/side-nav/side-nav.vue
src/renderer/components/top-nav/top-nav.vue
src/renderer/components/watch-video-comments/watch-video-comments.vue
src/renderer/components/watch-video-info/watch-video-info.vue
src/renderer/components/watch-video-live-chat/watch-video-live-chat.vue
src/renderer/components/watch-video-playlist/watch-video-playlist.vue
src/renderer/main.js
src/renderer/views/About/About.js
src/renderer/views/Channel/Channel.vue
src/renderer/views/Popular/Popular.vue
src/renderer/views/Search/Search.vue
src/renderer/views/Subscriptions/Subscriptions.vue
src/renderer/views/Trending/Trending.vue
src/renderer/views/Watch/Watch.vue

---
Webpack bundle dependencies
---
This pull request makes various changes to reduce FreeTube's package size. The first major one is allowing webpack to bundle the dependencies, this means that only the code that actually used is included in the final build (webpack failed to bundle both ytsr and ytpl, so for the moment they will still be included as is in the final package).
Bundling your code and dependencies is recommended by the [Electron performance guidelines](https://www.electronjs.org/docs/latest/tutorial/performance/#7-bundle-your-code), `electron-builder` however defaults to packaging all non dev dependencies in the node_modules directory into your package, which blows up the package size unnecessarily.
As the default behaviour of …

Webpack bundle dependencies

---

conflicts.yml
dummy-conflicts.yml

---
PR label automation conflicts
---
https://github.com/FreeTubeApp/FreeTube/issues/1720
Other workflows will hopefully get added soon. All workflows i tested do not work at the moment when opened from forks. I have created issues for them but most of them seem to be abandoned because of this reason :(
All workflows have been extensively tested in https://github.com/FreeTubeApp/Test-Repo
1. Fork https://github.com/FreeTubeApp/Test-Repo
2. create a PR from the fork
3. add the waiting for review label
4. create conflict
5. conflict label and comment gets added to notify author of PR
6. resolve conflict
7. conflict label will be removed and waiting for review …

PR label automation conflicts

---

src/renderer/views/Watch/Watch.js

---
Localization inconsistency fix for Local API
---
closes FreeTubeApp#2530
This applies a workaround for the inconsistency in the responses from `ytdl` and `ytpl`. The result of this change is that the video title and description are localized to `en-US` by `ytdl` (as it was expected to be based on the following code snippet).
```js
// line 353 of src\renderer\store\modules\ytdl.js
ytdl.getInfo(videoId, {
lang: 'en-US',// this locale was not being honored before this change
requestOptions: { agent }
}).then((result) => {
resolve(result)
}).catch((err) => {
reject(err)
})
```
Before this change:
After this change:
**Desktop (please complete the …

Localization inconsistency fix for Local API

---

src/renderer/components/ft-video-player/ft-video-player.js

---
Increase width of quality selector so that 1080p60 doesn't overflow into the full screen button
---
Fix the quality selector button overflowing into the full screen button when it has wide values like 1080p60 in it.
before:
after:
https://www.youtube.com/watch?v=zCLOJ9j1k2Y (select 1080p60)
- OS: Windows

Increase width of quality selector so that 1080p60 doesn't overflow into the full screen button

---

.github/workflows/build.yml
.github/workflows/release.yml
_scripts/build.js

---
Build and release 7zip artifacts
---
closes #2009
This pull request makes electron-builder build 7-zip archives in addition to the current zip ones. 7-zip has better compression the archives are smaller resulting in faster downloads. The Windows x64 7-zip archive is 29.8MB smaller than the zip archive.
I tested local builds with `yarn build` and triggered this workflow run on my fork: https://github.com/absidue/FreeTube/actions/runs/3024373522
- OS: Windows

Build and release 7zip artifacts

---

src/renderer/store/modules/sponsorblock.js

---
Don't log any errors if there are no SponsorBlock segments
---
The SponsorBlock API returns 404 if it doesn't have any segments for a video, currently this logs 4 messages to the console. As segments not being available is expected behaviour, we don't need to log anything.
No SponsorBlock segments: https://youtu.be/qim2Y6v_4EI
Has SponsorBlock segments: https://youtu.be/zy2a47e-Qao
- OS: Windows

Don't log any errors if there are no SponsorBlock segments

---

package.json
yarn.lock

---
Remove unneeded electron-builder-squirrel-windows dependency
---
Related to #2113
Squirrel builds were removed in #2113, this pull request removes the now unneeded `electron-builder-squirrel-windows` dependency.
I tested `yarn build` and nothing broke.
- OS: Windows

Remove unneeded electron-builder-squirrel-windows dependency

---

.github/workflows/super-linter.yml

---
Use slim linter option for super linter
---
Speeds up Super Linter workflow
The slim github/super-linter:slim-v4 comes with all supported linters but removes the following:
- rust linters
- dotenv linters
- armttk linters
- pwsh linters
- c# linters
"By removing these linters, we were able to bring the image size down by 2gb and drastically speed up the build and download time. The behavior will be the same for non-supported languages, and will skip languages at run time."
I also removed some comments that were not needed
- OS: Windows

Workflow: Use slim instead of full super linter

---

src/renderer/components/ft-input/ft-input.js

---
#2512: Update search suggestions on input
---
closes #2512
I added a watcher to the input component so that `this.updateVisibleDataList()` is triggered when the dataList prop changes.

#2512: Update search suggestions on input

---

_scripts/webpack.main.config.js
_scripts/webpack.renderer.config.js
_scripts/webpack.workers.config.js
package.json
yarn.lock

---
Remove node-loader as we don't have any binary/native node modules
---
Neither FreeTube or any of it's dependencies use binary/native node modules (`.node` file extension), so we don't need to use `node-loader`.
`yarn dev` and `yarn build` (you can also test just the webpack build with `yarn run pack`)
- OS: Windows

Remove node-loader as we don't have any binary/native node modules

---

_scripts/webpack.renderer.config.js
_scripts/webpack.web.config.js
src/datastores/handlers/index.js
src/index.ejs
src/renderer/App.js
src/renderer/components/ft-video-player/ft-video-player.js
src/renderer/components/general-settings/general-settings.js
src/renderer/components/top-nav/top-nav.js
src/renderer/components/watch-video-live-chat/watch-video-live-chat.js
src/renderer/components/watch-video-playlist/watch-video-playlist.js
src/renderer/main.js
src/renderer/store/modules/settings.js
src/renderer/store/modules/utils.js
src/renderer/views/Channel/Channel.js
src/renderer/views/Settings/Settings.js
src/renderer/views/Subscriptions/Subscriptions.js
src/renderer/views/Trending/Trending.js
src/renderer/views/Watch/Watch.js

---
Electron variable at build time instead of at runtime
---
This PR replaces the current runtime electron detection with build time variables, this allows webpack to optimise out (dead code elimination) web stuff in the electron build and vice versa. Unfortunately the define plugin doesn't seem to affect `.vue` files so for the Settings page i still needed to use a computed property but I was able to change it to use the variable, so it's still an improvement. 80KB drop doesn't seem too bad to me :).
@MarmadileManteater This should also be useful to you for the web build. With some adjustments you will be able to achieve even better results than the Electron build (e.g. excluding local API stuff).
`renderer.js`: …

Electron variable at build time instead of at runtime

---

src/renderer/store/modules/utils.js

---
Fixing an undefined function reference
---
This replaces a use of `this.showToast` with `dispatch("showToast",` inside of `src\renderer\store\modules\utils.js` because `this.showToast` is not defined.
before:
after:
In order to reach this code, the download path must be a path which does not exist. Then, there needs to be an error during the creation of the directory. 
An easy way to test this would be to set the download path to a path the user would have access to read but not write like `C:/Program Files/test test test`. If you create that folder, select it as the download path, and then, …

Fixing an undefined function reference

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/workflows/autoLabelIssue.yaml
README.md

---
Add MPR to Unofficial Downloads
---
Closes #2130
Add MPR link to Unofficial Downloads section in README
N/A (screenshot of MPR package page isn't too interesting)
Yes (Markdown preview was used)
- OS: Debian- and Ubuntu-based distros
- OS Version: Debian 11.5 (Bullseye) or newer, Ubuntu 22.04 (Jammy Jellyfish) or newer
- FreeTube version: 0.17.1+
N/A

Add MPR to Unofficial Downloads

---

src/renderer/components/ft-list-channel/ft-list-channel.js
src/renderer/components/ft-list-video/ft-list-video.js
src/renderer/components/playlist-info/playlist-info.js
src/renderer/components/watch-video-info/watch-video-info.js
src/renderer/views/Channel/Channel.js
src/renderer/views/Watch/Watch.js

---
Properly localize numbers
---
closes #2547
Number seperators (",", "." and " ") were not chosen based on locale and were always shown as ","
Used search with different locales (had to clear search to test)
- OS: Windows

Properly localize numbers

---

src/renderer/views/Watch/Watch.js

---
Fix the localised description containing broken URLs
---
Follow up to #2535
Closes #2578
This pull request fixes the truncated links in the localised video description, making them valid URLs so that `autolinker` can properly link them.
Before:
After:
**Testing**
https://www.youtube.com/watch?v=zcchDu7KoYs
This video's description has a bunch of tricky things like timestamps, links to other videos, the special URL `http://www.youtube.com/approachingnirvana` and the lttstore link has utm tracking parameters.
- OS: Windows

Fix the localised description containing broken URLs

---

_scripts/webpack.main.config.js
package.json
src/main/index.js
yarn.lock

---
Fully replace electron-debug with our own implementation
---
This pull removes the `electron-debug` dependency and adds our own implementation for the features that we didn't already have our own implementations for. There are various advantages to getting rid of that dependency and replacing it with our own implementations:
1. Our keyboard shortcuts will work on release builds, which is fine as this isn't a proprietary app, so being able to debug easily on release builds is quite useful.
2. electron-debug was causing issues with our release webpack builds, getting rid of the dependency, means we don't need to mark it as external in the webpack config.
3. this also gets rid of 6 development dependencies which is nice, also our implementation uses …

Fully replace electron-debug with our own implementation

---

src/main/index.js

closes #1535
Implement last window's fullscreen state
Lazy to take video
- open app
- switch to full screen
- quit app
- open app, confirm window is in full screen
- switch from full screen
- quit app
- open app, confirm window is not in full screen
- OS: MacOS
- FreeTube version: 70481b4880a71bed4dc28c6a6321fc7cf849f0cd

Implement last window's fullscreen state

---

src/renderer/views/Watch/Watch.sass

---
Set height of watch page grid with auto in dual-column-template
---
closes #2587
Sets the height of the grid-template with auto instead of 1fr.
This ensures the page doesn't keep scrolling for longer than necessary if live chat is enabled and recommended videos is disabled
look at the scroll bar on the right.
Zoom in might be required to
before:
after:
**Testing**
I've tested all combinations of live chat and recommend videos being enabled and disabled.
There should be no difference except for when only live chat is enabled with dual column template
**Desktop:**
- OS: Linux
- OS Version: 5.19.7-arch1-1

Set height of watch page grid with auto in dual-column-template

---

src/renderer/store/modules/utils.js

---
Implementing downloadMedia when IS_ELECTRON is false
---
This PR adds two lines to `utils` to implement `openExternalLink` and `downloadMedia` in builds where `IS_ELECTRON` is set to `false`.
These screenshots are from a web build produced by my fork before and after these changes were applied to it.
*Before:*
*After:*

Implementing download media when IS_ELECTRON is false

---

src/renderer/components/ft-input/ft-input.js

---
Fixing issue with visibleDataList holding onto stale data
---
This PR intends to fix an unintentional bug introduced by FreeTubeApp#2567. 
When selecting an invidious instance in the settings, the dropdown which displays possible instances will only update when the view is mounted. The result is that you can not get the dropdown to populate with invidious instances other than the current instance at the time the view was mounted:
The core issue is that the call to `updateVisibleDataList` was moved out of `handleInput` and into the watch method for `dataList`; however, there was no watch method added `inputData`, This means that `visibleDataList` sometimes retains stale data when it should be …

Fixing issue with visibleDataList holding onto stale data

---

src/renderer/components/data-settings/data-settings.js
src/renderer/components/ft-list-video/ft-list-video.js
src/renderer/components/ft-share-button/ft-share-button.js
src/renderer/components/playlist-info/playlist-info.js
src/renderer/components/watch-video-comments/watch-video-comments.js
src/renderer/components/watch-video-playlist/watch-video-playlist.js
src/renderer/store/modules/utils.js
src/renderer/views/Channel/Channel.js
src/renderer/views/Search/Search.js
src/renderer/views/Subscriptions/Subscriptions.js
src/renderer/views/Trending/Trending.js
src/renderer/views/Watch/Watch.js
static/locales/en-US.yaml

---
Cleaning up calls to the Clipboard API
---
I have found some issues with the current usage of the clipboard API in FreeTube. `navigator.clipboard.writeText` returns a promise, but most of the code that uses it in FreeTube doesn't seem to acknowledge that; this can lead to unexpected behavior.
```javascript
// line 337 of src/renderer/components/ft-list-video/ft-list-video.js
navigator.clipboard.writeText(this.invidiousChannelUrl)
this.showToast({// we don't necessarily know if writeText is successful when this executes
message: this.$t('Share.Invidious Channel URL copied to clipboard')
})
```
```javascript
// line 115 of src/renderer/components/ft-share-button/ft-share-button.js
this.showToast({ …
```

Cleaning up calls to the Clipboard API

---

src/renderer/App.js
src/renderer/components/proxy-settings/proxy-settings.js
src/renderer/store/modules/invidious.js
src/renderer/store/modules/sponsorblock.js
src/renderer/views/Watch/Watch.js

---
Replace jquery getJSON and get with native fetch
---
Original giant PR #2360
This PR replaces the calls to jquery's networking functions (`getJSON` and `get`) with the `fetch` API that is available in all browsers these days. It doesn't remove the jquery dependency as it's still used in quite a few other places in FreeTube, I'll change those in future PRs.
The idea is to split up my giant jquery PR into smaller more manageable ones, as that makes them easier to test and less likely that bugs sneak into them.
1. Update check
Set version in the `package.json` file to `0.16.0` and check that the "Update available..." banner shows up
2. Proxy test
Click the …

Replace jquery getJSON and get with native fetch

---

src/renderer/views/Watch/Watch.js

---
Improve premiere timestamp to be easier to read
---
no related issue that i know of
Changes the premiere timestamp to be easier to read.
Removes year and seconds from string because they are not important.
Displays month as it's "long name" (eg., March)
also displays timestamp in the same locale set in freetube.
before:
my locale
after:
my locale / system default
english locale
french locale
I have tested some different locales in freetube.
Open this in browser and you …

Improve premiere timestamp to be easier to read

---

.eslintrc.js
src/main/index.js
src/renderer/App.js
src/renderer/components/data-settings/data-settings.js
src/renderer/components/ft-list-dropdown/ft-list-dropdown.js
src/renderer/components/ft-list-video/ft-list-video.js
src/renderer/components/ft-profile-edit/ft-profile-edit.js
src/renderer/components/ft-video-player/ft-video-player.js
src/renderer/components/general-settings/general-settings.js
src/renderer/components/playlist-info/playlist-info.js
src/renderer/components/top-nav/top-nav.js
src/renderer/components/watch-video-comments/watch-video-comments.js
src/renderer/components/watch-video-info/watch-video-info.js
src/renderer/components/watch-video-live-chat/watch-video-live-chat.js
src/renderer/components/watch-video-playlist/watch-video-playlist.js
src/renderer/i18n/index.js
src/renderer/store/modules/invidious.js
src/renderer/store/modules/utils.js
src/renderer/store/modules/ytdl.js
src/renderer/views/Channel/Channel.js
src/renderer/views/Playlist/Playlist.js
src/renderer/views/Popular/Popular.js
src/renderer/views/ProfileSettings/ProfileSettings.js
src/renderer/views/Search/Search.js
src/renderer/views/Subscriptions/Subscriptions.js
src/renderer/views/Trending/Trending.js
src/renderer/views/Watch/Watch.js
static/pwabuilder-sw.js

---
Remove console.logs
---
Remove console.log & add lint rule to prevent logging to console
- OS: Windows

Remove console.logs

---

src/renderer/components/data-settings/data-settings.js
src/renderer/components/data-settings/data-settings.vue
src/renderer/store/modules/utils.js

---
Implementing `showOpenDialog`'s web callback
---
This PR implements `showOpenDialog`'s web callback, and in order to do that meaningfully, it also refactors the `import` functions in `data-settings` (`importHistory`, `importPlaylists`, `importSubscriptions`, etc) to use a new utility function called `readFileFromDialog` instead of `fs.readFile`.
```javascript
/**
* @param {Object} response the response from `showOpenDialog`
* @param {Number} index which file to read (defaults to the first in the response)
* @returns the text contents of the selected file
*/
async readFileFromDialog(context, { response, index = 0 }) {
return await new Promise((resolve, reject) => {
if (process.env.IS_ELECTRON) {
// …
```

Implementing showOpenDialog's web callback

---

src/renderer/store/modules/invidious.js

---
Replace jquery $.param with native URLSearchParams
---
This pull request replaces jquery's param function with the native URLSearchParams class.
Try a few things with the Invidious API selected e.g. searching
- OS: Windows
This is another PR in your favourite series: replacing jquery with absidue

Replace jquery $.param with native URLSearchParams

---

src/renderer/App.js
src/renderer/components/ft-video-player/ft-video-player.js

---
Use native addEventListener instead of jquery's .on
---
This pull request uses the native `.addEventListener` method instead of jquery's `.on`. The `event.key` property unfortunately will contain an upper case or lower case letter in it depending on whether the shift or caps lock key are enabled but it's the only property that is not deprecated and also respects the user's keyboard layout, so it's the one I've used for this PR.
**Testing**
They should all behave the same as they did before:
- Global keyboard events like focusing the search bar
- Player keyboard events like seeking with the numbers, pausing, skipping frames, taking a screenshot etc
- Right, middle and left clicking on links in video descriptions
**Desktop (please complete the …

Use native addEventListener instead of jquery's .on

---

src/renderer/components/top-nav/top-nav.js
src/renderer/components/top-nav/top-nav.vue

---
Replace jquery in top-nav component
---
Gets rid of jquery in the top-nav component, replacing it with vue refs, v-show and native `.classList.add()` and `.classList.remove()`.
Everything should still work the same:
- History back and forwards buttons
- Showing and hiding the search bar when the window is narrower than 680 pixels
- OS: Windows
What is a jquery?

Replace jquery in top-nav component

---

src/index.ejs
src/renderer/App.js
src/renderer/components/external-player-settings/external-player-settings.js
src/renderer/components/general-settings/general-settings.js
src/renderer/components/watch-video-comments/watch-video-comments.js
src/renderer/store/modules/invidious.js
src/renderer/store/modules/settings.js
src/renderer/store/modules/utils.js
src/renderer/views/Watch/Watch.js

---
Fix some development code not getting optimised out
---
Webpack doesn't know about vue's computed properties or vuex stores, so it doesn't know how to optimise them out. This PR fixes that by marking development only code in a way that webpack understands, so it can remove the dead code properly while optimising the release builds. This PR also gets rid of some unnecessary `isDev` computed properties. This change doesn't make a big size or speed difference but even a 849 byte decrease in size and an unmeasurably small performance improvement are better than including dead code in a release …

Fix some development code not getting optimised out

---

src/main/index.js

---
Remove explicitly disabling CORS. issue is fixed upstream
---
no related issue
On electron `v9.0.4` CORS was not disabled by `webSecurity: false`
This was fixed in https://github.com/electron/electron/pull/25463
This line should no longer be needed.
I've tested Local API and Invidious API.
tested some videos/live streams and made sure comments, description, etc were loaded.
**Desktop:**
- OS: Arch Linux
- OS Version: 5.19.8-arch1-1
- FreeTube version: 0.17

Remove explicitly disabling CORS. issue is fixed upstream

---

_scripts/build.js

---
Small build config cleanup
---
Cleanup some whitespace and an unused variable in the build.js script
**Testing**
Doesn't break anything but you can test with `yarn build` just to be sure
**Desktop:**
- OS: Windows

Small build config cleanup

---

src/renderer/components/watch-video-description/watch-video-description.js
src/renderer/components/watch-video-description/watch-video-description.vue

---
Fix empty description box showing for the Invidious API
---
This pull request fixes an empty description box showing for videos that don't have a description when the Invidious API is selected. I noticed this problem while removing jquery from the description component so I've killed (fixed) two birds (issues) with one stone (PR).
before:
after:
https://youtu.be/Dmu-Yt4Nzzs (from #2530)
- OS: Windows
jquery is used in a lot of places

Fix empty description box showing for the Invidious API

---

src/renderer/components/ft-icon-button/ft-icon-button.js
src/renderer/components/ft-icon-button/ft-icon-button.sass
src/renderer/components/ft-icon-button/ft-icon-button.vue
src/renderer/components/ft-share-button/ft-share-button.js

---
Replace jquery in ft-icon-button with vue functionality
---
This pull request replaces the use of jquery for the `ft-icon-button` component with vue's `v-show` and refs. Also managed to clean the code up a bit while I was at it.
**Testing**
The `ft-icon-button` component is used in all of these places:
- Reload button on the trending, subscriptions and popular tabs
- Three dots button dropdown in video lists
- Settings button in the profile selector dropdown
- Share and download button etc on the watch page
- OS: Windows
jquery who?

Replace jquery in ft-icon-button with vue functionality

---

src/renderer/store/modules/invidious.js

Fixing issue instance list not falling back to the local instance list or the hardcoded list
This PR expands the fall-back condition for the fetch to the invidious instances list to catch all cases where the instances list returns an empty response. I don't know if this is a super regular thing, but right now as I type this, the URL [https://api.invidious.io/instances.json](https://api.invidious.io/instances.json) isn't throwing an error, but it isn't giving back any useful information either. Instead, it is handing back an empty array `[]` with a status code of `200`. 
This won't throw an error when retrieved via `await fetch`, and thus, it won't trigger the fall-back to use the local `json` list of invidious instances or even the hardcoded list. Since it does not trigger the fall-back, …

Fixing issue with instance list not falling back

---

src/renderer/App.js
src/renderer/views/About/About.js

This pull request fixes webpack embedding the entire package.json file in the renderer.js file for release builds. My guess is that when we import it with `require()` webpack treats it at a commonjs file and doesn't treeshake it. When it's imported with an es6 import, webpack properly treeshakes it and gets rid of the rest of the JSON. It only makes about a 1KB difference to the size of the renderer.js file but it was a small easy fix so it seems worth it anyway.
I didn't use the named import for the `version` property, as webpack complained that using named imports for JSON is being deprecated. When I looked it up apparently it's because the web standards people decided that JSON should be treated as a single thing. https://github.com/tc39/proposal-json-modules#why-dont-json-modules-suppo …

Fix package.json getting embedded in the release builds

---

src/renderer/components/theme-settings/theme-settings.js
src/renderer/components/theme-settings/theme-settings.vue

MarmadileManteater#24
The "Disable smooth scroll" setting requires the restart of electron, so this PR hides that setting when not in electron, Additionally, I found this `FIX ME` in the `handleSmoothScrolling` function because there is no electron safeguard. This change would introduce that safeguard.
*Before: (in a web build)*
*After: (in a web build)*

Hiding "Disable smooth scroll" option in web

---

src/renderer/components/ft-video-player/ft-video-player.js

This pull request stops using jquery to create the video player buttons. It uses `document.createElement()` and `button.appendChild` to create and insert the elements into the DOM.
- DASH quality selector
- screenshot button
- theatre mode toggle
- full window button
- loop button

Create video player buttons without jquery

---

src/main/index.js
src/renderer/App.js
src/renderer/components/ft-input/ft-input.js
src/renderer/components/top-nav/top-nav.js

Improvement over #2427
Update search in new window function to also copy original query text to new window search input
https://user-images.githubusercontent.com/1018543/192958721-de3e8da5-cbec-4cda-930d-4c969b9d2857.mov
- Enter search text in top nav text input
- Shift enter/click
- Check new window top nav text input
- **OS:** MacOS
- **OS Version:** 12.6
- **FreeTube version:** e0c3f47c6c4b31e6734c2993eeff59c494ee056e
- Text is only copied for search query, not for video/playlist/channel

Update search in new window function to also copy original query text to new window search input

---

src/renderer/components/subscription-settings/subscription-settings.js
src/renderer/components/subscription-settings/subscription-settings.vue
src/renderer/store/modules/settings.js
src/renderer/views/Subscriptions/Subscriptions.js
src/renderer/views/Subscriptions/Subscriptions.vue
static/locales/en-US.yaml

closes #2515
part of #539
Adds a new setting in subscription settings to disable automatic fetching of the subscription feed.
Prevents calls to the method `getSubscriptions()` in` Subscriptions.js` in to places.
1. When the subscriptions component is mounted
2. In `getProfileSubscriptions` method, when the users switches profile.
When the users switches profile and has disabled auto fetching 2 things can happen
1. the video list is emptied.
2. if the video list is saved in `profileSubscriptions` then it will be loaded instead.
In `Subscriptions.vue` I made some changes to the messages that show when the video list is empty
1. The regular "You have not subscribed to any channel" message will now only show when you have in fact not subscribed to any channel.
2. Added a new message that only …

Add setting to disable automatic fetching of subscription feed

---

_scripts/webpack.renderer.config.js
_scripts/webpack.web.config.js

follow up to #2603
`js-yaml` is only used to load the languages for the development builds, as the language files are converted to JSON and compressed during the release build process. Unfortunately webpack doesn't notice that `js-yaml` isn't needed in the release builds and still includes it in the renderer.js file. This pull request fixes that by explicitly telling webpack to ignore the `js-yaml` import for the release builds.
before:
after:
`yarn build` and then change that language to make sure that locales are still loaded properly.

Fix the development only js-yaml dependency being included in the release builds

---

src/renderer/i18n/index.js

This PR formats the URLs used to fetch the locale json (in web builds) to be more consistent using `path.join`. Currently, the URLs that are being fetched can end up looking like this: `path/to/freetube//static/locales/${locale}.json` because of a trailing `/` inside of the path. This typically works fine because it often gets interpreted as `path/to/freetube/static/locales/${locale}.json` which is where the files are actually stored, but if a web build is stored on a server which is more particular about paths or if FreeTube is in Cordova, this causes an error.
*Before* (on Android in Cordova in my fork)
*After* (on Android in Cordova in my fork)
This should only effect locales fetching when `IS_ELECTRON` is `false`. 
- OS: Windows …

Prevent adding extra `/` when concatenating locale paths

---

src/renderer/components/top-nav/top-nav.js

This PR adds a condition to the window `resize` event listener which prevents the search bar from closing unless the width of the page has changed. On mobile, the screen height may change when opening a virtual keyboard, but the screen width does not typically change. This change should prevent issues with the search bar closing when opening a virtual keyboard.
*before* (on Android in my fork)
*after* (on Android in my fork)
This would also effect Electron builds. I am open to modifying this PR to only change the existing behavior when `IS_ELECTRON` is …

Prevent search from closing when using a virtual keyboard

---

src/renderer/components/ft-prompt/ft-prompt.css

The update prompt card is a little off center and overflows the window if the window is too small. This PR properly centers the update prompt card vertically and horizontally inside of the window.
This might look good with some additional padding.

Centering update prompt card

---

src/renderer/components/watch-video-live-chat/watch-video-live-chat.css
src/renderer/components/watch-video-live-chat/watch-video-live-chat.js
src/renderer/components/watch-video-live-chat/watch-video-live-chat.vue

This pull request removes jqeury from the live chat component, some cleanup and fixes the emojis messing up the layout of the messages.
There is a visible change but i didn't want to screenshot and post live chat comments here
- Add my updated fork of youtube-chat (includes the open PR) `yarn add https://github.com/absidue/youtube-chat`
- Pick a live stream from https://www.youtube.com/live/
- Check that the live chat scrolls and that the scroll to bottom button shows up when you scroll and also works

Replace jquery in live chat and improve the message styling

---

src/renderer/components/ft-card/ft-card.vue
src/renderer/components/ft-profile-selector/ft-profile-selector.css
src/renderer/components/ft-profile-selector/ft-profile-selector.js
src/renderer/components/ft-profile-selector/ft-profile-selector.vue

This pull request replaces jquery in the profile selector component with vue and native javascript stuff. A lot of the logic is identical to the ft-icon-button component.
- Changing profiles
- Opening the profile settings

Replace jquery in the profile selector

---

src/renderer/App.vue
src/renderer/views/Trending/Trending.js
src/renderer/views/Trending/Trending.vue

This pull request removes jquery from the trending page and replaces it with vue's dynamic props and event handling. It also fixes issues with the tabs not getting focused properly, which should make the keyboard navigation side of things a lot more pleasant.
- Changing tabs on the trending page
- Navigating the tabs with the left and right arrow keys
- Changing tab with enter or space
jay query is almost gone

Replace jquery on the trending page

---

package.json
yarn.lock

closes #2360 
This is the last pull request in the jquery removal series.
Highlights:
- Dropped 88kb from renderer.js output
- Better (maybe not noticeable) performance as we are now using the native stuff directly
- Had a chance to clean up some components
- One less dependency
As all references to jquery are gone, webpack doesn't bundle it in anymore, so this PR doesn't break anything.

Remove the now unused jquery dependency

---

src/renderer/components/ft-toast/ft-toast.js

`setImmediate` is a global in node, but it is technically also part of the `timers` module, and it is not a global in web. This causes an error to occur when `showToast` is called in a browser.
_Before: (in a web build)_
_After:_
This change can be tested by checking if any toast messages display in both electron and web environments.
This error did not occur in my original web build because `setImmediate` was being globally defined, but I believe it makes more sense to import it explicitly as to not pollute global scope. Technically, this same behavior …

Replacing `setImmediate` with `setTimeout`

---

src/renderer/store/modules/invidious.js

This pull request removes the unused `isGetChannelInfoRunning` property from the invidious store. I couldn't find any other references to that property so it doesn't seem worth keeping it around.
Technically in vuex 3 it's all one big store, the concept of separate stores only exists in Pinia.
Channel pages and fetching subscriptions still work fine.

Remove unused property from the invidious store

---

src/renderer/videoJS.css

The vjs controls overflow the window when the window is small. This PR hides some of the vjs controls under certain conditions in order to help with this overflow issue. When the window is less than `680px` width, it hides the `picture and picture` button (when it is disabled), and the `full window` button (when vjs is not currently in the `full window mode`). 
_Before/After:_ (in web)
_Before/After:_ (in electron)
I personally feel like the `full window` button is superfluous when the screen width is below 680px due to existing media queries.
In my fork, …

Reducing overflow in the vjs video player

---

src/renderer/App.js

This PR intends to fix an issue which was causing the link around the video title in `ft-list-video` to trigger `openExternalLink` erroneously. This problem occurs because the link surrounding the title in `ft-list-video` does not contain a `span` element, and all other internal links seem to contain some sort of element, so the `event.target.tagName === 'A'` condition had been catching all of the the internal links without even needing the check for `http`. 
The check for `http` at the beginning of a link doesn't work is because it uses the `.href` property of the link element which is computed using the real attribute value `#/watch/{someVideoId}` and the current window location. The result is a link that looks like `http://localhost:9080/#/watch/{someVideoId}` which is technically …

Fixing the logic for `isExternalLink`

---

README.md

Notable things that I've done:
- Ordered the headings in a more logical structure for readers
- removed some sentences that were redundant 
- removed browser extension disclaimer because the link didn't provide the adequate info anymore and couldn't find a good replacement
I think its better to go to https://github.com/efb4f5ff-1298-471a-8973-3d47447115dc/FreeTube/blob/marketing/README.md
Need your help/opinion on:
- Did i miss some features that we should definitely list?
- Should we update our pictures to show more of our features?
- i've made the nighly builds header smaller because it is a subset of the official downloads but the header is now the same size as plain text. Should i revert this change?
- Do we want to add badges/widgets in the same way …

Advertise FT better in README

---

_scripts/webpack.web.config.js
package.json
yarn.lock

We've been using vue-loader for the electron renderer without specifying an options for a while now without any issues. This pull request updates the webpack config for the web build to do the same. This doesn't change the build output as vue-loader already has a dependency on vue-style-loder and uses it internally, which also means we can get rid of the explicit vue-style-loader dependency in our package.json. I also got rid of the unused style-loader dependency (vue-style-loader is vue's fork of style-loader).
`yarn pack:web`
I used `git diff --no-index dist dist2` to compare the dist/web directory with and without these changes and the output was identical.

Cleanup the web webpack config

---

src/renderer/views/Popular/Popular.js
src/renderer/views/Subscriptions/Subscriptions.js
src/renderer/views/Trending/Trending.js

closes #2631
Adds shortcuts to the 3 views with refresh buttons.
I stole the keyboard shortcut handler function from ft-video-player.js
Just a quick implementation.
No visible Difference
Testing should be done on all three views
- Pressing `R` When the view isn't loading should perform the same action as the refresh button.
- Nothing should happen if `R` is pressed while the view is loading
- Leaving the view should destroy the event handler and pressing `R` should no longer do anything
- Typing `R` into a input element. such as the search box should not trigger a refresh.
- **OS:** Arch Linux
- **OS Version:** 5.19.13-arch1-1
Since everything uses the same implementation with only differences being which function to call there ends up being a lot of code …

Add shortcuts for refresh buttons on Subscription, Trending, and Popular views

---

.github/workflows/report.yml

raised in https://github.com/FreeTubeApp/FreeTube/issues/2436#issuecomment-1272358737 by @linuxgirl22 confirmed in https://github.com/FreeTubeApp/FreeTube/issues/1623
There were several issues with this workflow:
1. When adding or removing a random label this workflow would delete this issue from the project board or add this issue to the project board.
2. When issue gets closed it removes the issue from the project board but when an issue gets reopened it didnt add the issue back to the project board
3. This workflow also move issues from bucket X to the to assign bucket under certain edge cases when adding labels / removing labels
Nr 1/3. fixed by removing the `labeled` and `unlabeled` logic more info on why i did this in 'Additional context'
Nr 2. fixed by adding some adding some code …

Fix project board workflow

---

src/renderer/components/side-nav/side-nav.vue
src/renderer/components/top-nav/top-nav.vue

no issue that I know of
related PR https://github.com/FreeTubeApp/FreeTube/pull/2696 can be closed in favor of this.
- Replaces `@keypress` with `@keydown.enter.prevent`
- The buttons will now only trigger when enter is pressed
- Adds `role="button"` and `tabindex="0"` to _New _Window_ Button in top-nav
- It can now be selected when "tabbing" just like the other buttons
- Adds `@keydown.enter.prevent` to _Channel_ button in sidebar
- It can now be navigated to using only keyboard keys
This fixes issues where user would use a shortcut but also trigger the last used button in the top-nav.
One particulary annoying one is:
1. Go to a video.
2. From there go to any other video or page.
3. Press the back button to go back to the video.
4. Press `S` to toggle full window mode.
5. notice that you …

Remove deprecated @keypress + some accessability improvements

---

_scripts/dev-runner.js
src/main/ImageCache.js
src/main/index.js
src/renderer/components/experimental-settings/experimental-settings.css
src/renderer/components/experimental-settings/experimental-settings.js
src/renderer/components/experimental-settings/experimental-settings.sass
src/renderer/components/experimental-settings/experimental-settings.vue
src/renderer/components/ft-toggle-switch/ft-toggle-switch.js
src/renderer/components/ft-toggle-switch/ft-toggle-switch.vue
src/renderer/views/Settings/Settings.js
src/renderer/views/Settings/Settings.vue
static/locales/en-US.yaml

---
Disable http disk cache and implempent in-memory image cache
---
#1837 could be related but I'm not sure
Thank you to the Matrix user for bringing this issue to our attention.
To reduce RAM usage electron stores the http cache on disk. While that might be alright for other applications, in FreeTube that means that while you are watching a video, all of the buffered video data is actually being constantly streamed to and from your disk. In the long term this will likely have an inpact on disk health.
This pull request is made up of two parts:
1. Disabling the http cache, unfortunately there doesn't seem to be a way to get rid …

Disable http disk cache and implempent in-memory image cache

---

src/renderer/components/ft-video-player/ft-video-player.css

N/A
Current chapter markers look "fat" and also might be confused with SponsorBlock markers
This PR make it look closer to Youtube one
Not sure if it looks better if box shadow is added
Old
Videos for testing:
- https://youtu.be/tHNQOJ_nsLc
- Most recent videos from https://youtube.com/channel/UCXuqSBlHAE6Xw-yeJA0Tunw
- **OS:** MacOS
- **OS Version:** 12.6
- **FreeTube version:** 64679ca1ce28a773cc01c39b162c7613ed4b2a5b

Update chapter marker style

---

package.json
yarn.lock

Same as https://github.com/FreeTubeApp/FreeTube/pull/5465 but targetting the master branch so that we can do a hotfix release with it, please see that pull request for details.

Update YouTube.js to 10.2.0

---

package.json
src/main/index.js
src/renderer/helpers/api/local.js
src/renderer/helpers/colors.js
src/renderer/helpers/utils.js
src/renderer/views/Watch/Watch.js
yarn.lock

N/A
https://github.com/FreeTubeApp/FreeTube/pull/5507 + https://github.com/FreeTubeApp/FreeTube/pull/5472 for `master`
N/A
See related PRs
- **OS:**
- **OS Version:**
- **FreeTube version:**

(Master) Update YouTube.js 10.3.0 & Use streams from the iOS client to workaround playback issues

---

package.json
src/renderer/helpers/api/local.js
yarn.lock

Bump youtubei.js from 10.5.0 to 12.2.0 + Bump version number to from v022.0 to v0.22.1 + Fix incompatibility with upcoming YouTube.js version

---

.github/workflows/release.yml

Original PR: #6751
This pull request cherry picks #6751 (Change the release workflow to accept the release ID as an input) to the master branch, please see the original pull request to the development branch for the full description and a screenshot.

Cherry pick: Change the release workflow to accept the release ID as an input (#6751)

---

package.json
yarn.lock

See https://github.com/FreeTubeApp/FreeTube/pull/6867
Also bumps version number

Bump youtubei.js from 13.0.0 to 13.1.0

---

.github/workflows/flatpak.yml

This updates the Flatpak build script to fix an issue where a file wasn't being updated properly and also updates the script to no longer need the upload_id secret.
I created a fork and tested the changes on a separate repo. Everything worked as intended.

Fix Flatpak Script to Work again and remove Upload ID secret
